<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_ShippingPrice
 * @version    1.0.2
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><?php
$productId = $this->getProductId();
$price = $this->getPrice();
?>
<?php if ($price === false): ?>
    <div class="price-box aw-shipping-price-box aw-shipping-price-box-<?php echo $productId; ?>" style="display:none;">
        <p class="minimal-price">
            <span class="aw-shipping-price-label"><?php echo $this->__('Shipping Price') ?>:</span>
            <span class="price aw-shipping-price aw-shipping-price-<?php echo $productId; ?>"></span>
        </p>
    </div>
<?php else: // show price ?>
    <div class="price-box aw-shipping-price-box aw-shipping-price-box-<?php echo $productId; ?>">
        <p class="minimal-price">
            <span class="aw-shipping-price-label"><?php echo $this->__('Shipping Price') ?>:</span>
            <span class="price aw-shipping-price aw-shipping-price-<?php echo $productId; ?>">
              <?php if (!$price): ?>
                <?php echo $this->__('Free') ?>
              <?php else: ?>
                <?php echo Mage::helper('core')->currency($price); ?>
              <?php endif; ?>
            </span>
        </p>
    </div>
<?php endif; ?>
