<style>
   .main-container.col1-layout{padding:0px;}
</style>
<div id="main-slider" class="owl-carousel">
   <div class="item">
      <div class="slider-product-main">
         <img src="/skin/frontend/smartwave/porto/images/slide-01-kantor.jpg" />
         <label> Fabelio Untuk Kantor</label>
      </div>
   </div>
   <div class="item">
      <div class="slider-product-main">
         <img src="/skin/frontend/smartwave/porto/images/slide-02-hotel.jpg" />
         <label> Fabelio Untuk Hotel </label>
      </div>
   </div>
   <div class="item">
      <div class="slider-product-main">
         <img src="/skin/frontend/smartwave/porto/images/slide-03-restoran.jpg" />
         <label> Fabelio Untuk Restoran</label>
      </div>
   </div>
   <div class="item">
      <div class="slider-product-main">
         <img src="/skin/frontend/smartwave/porto/images/slide-04-rumah.jpg" />
         <label> Fabelio Untuk Rumah</label>
      </div>
   </div>
</div>
<div class="container">
   <div class="business-services-main">
      <h2>Who used our services</h2>
      <div class="business-services">
         <ul>
            <li>
               <img src="/skin/frontend/smartwave/porto/images/gojek-1.png" />
            </li>
            <li>
               <img src="/skin/frontend/smartwave/porto/images/lnc-1.png" />
            </li>
            <li>
               <img src="/skin/frontend/smartwave/porto/images/101-1.png" />
            </li>
            <li>
               <img src="/skin/frontend/smartwave/porto/images/brilio-1.png" />
            </li>
            <li>
               <img src="/skin/frontend/smartwave/porto/images/getcraft-1.png" />
            </li>
            <li>
               <img src="/skin/frontend/smartwave/porto/images/athentique-1.png" />
            </li>
         </ul>
      </div>
   </div>
   <div class="business-form">
      <div class="business-form-right">
         <h2>Daftar Layanan Konsultasi</h2>
         <div class="form-content">
            <div class="form-group">
               <label>Nama Kontak</label>	
               <input type="text" value=""/>
               <span>Nama Anda(beserta nama perusahaan jika ingin berkonsultasi untuk kantor, hotel dan/atau restoran)</span>
            </div>
            <div class="group-set">
               <div class="form-group">
                  <label>No. Handphone Kontak</label>
                  <input type="text" placeholder="Nomor" />
               </div>
               <div class="form-group email-form">
                  <label>Alamat Email Kontak</label>
                  <input type="text" placeholder="Email" />
               </div>
            </div>
            <button name="submit" type="submit" form="b2bform" value="Submit" class="business-form-btn" style="border:tomato;">Daftar</button>
         </div>
      </div>
      <div class="business-form-left">
         <p>Perencanaan matang mutlak dibutuhkan ketika merancang sebuah bangunan apapun ukurannya. Untuk itulah kami hadir, memastikan semuanya serasi dan selaras.</p>
         <div class="view-download">
            <div class="design-sol">
               <img src="/skin/frontend/smartwave/porto/images/design-solution-essentials.png" />
               <div class="view-download-icon">
                  <div class="view-icon">
                     <img src="/skin/frontend/smartwave/porto/images/view.svg" />
                     <label>View</label>
                  </div>
                  <div class="down-icon">
                     <img src="/skin/frontend/smartwave/porto/images/download.svg" />
                     <label>Download</label>
                  </div>
               </div>
            </div>
            <div class="fabelio-catalogue">
               <img src="/skin/frontend/smartwave/porto/images/fabelio-2016-catalogue.png" />
               <div class="view-download-icon">
                  <div class="view-icon">
                     <img src="/skin/frontend/smartwave/porto/images/view.svg" />
                     <label>View</label>
                  </div>
                  <div class="down-icon">
                     <img src="/skin/frontend/smartwave/porto/images/download.svg" />
                     <label>Download</label>
                  </div>
               </div>
            </div>
         </div>
      </div>
   </div>
   <div class="business-hotel">
      <div class="business-hotel-banner">
         <img src="/skin/frontend/smartwave/porto/images/display-image.png" />
         <label>Serahkan kepada ahlinya</label>
      </div>
      <div class="business-hotel-inner">
         <div class="business-hotel-box">
            <div class="business-hotel-box-img">
               <img src="/skin/frontend/smartwave/porto/images/icon-kantor.svg" />
            </div>
            <label>Kantor</label>
            <p>Sebagai tempat berkumpulnya tenaga profesional, tata ruang kantor selayaknya mencerminkan kompetensi dengan tetap mengutamakan kenyamanan.
               Untuk itu kami hadir membantu Anda mewujudkan suasana kantor yang dapat memacu produktifitas ke level yang lebih tinggi.
            </p>
         </div>
         <div class="business-hotel-box">
            <div class="business-hotel-box-img">
               <img src="/skin/frontend/smartwave/porto/images/icon-hotel.svg" />
            </div>
            <label>Hotel</label>
            <p>Selain pelayanan ramah, faktor penting dalam perkembangan sebuah hotel adalah tingkat kenyamanan yang
               melampaui ekspektasi. Pengalaman tak terlupakan bagi setiap tamu yang datang sangat mungkin diwujudkan 
               bersama tim kami yang kaya pengalaman.
            </p>
         </div>
         <div class="business-hotel-box">
            <div class="business-hotel-box-img">
               <img src="/skin/frontend/smartwave/porto/images/icon-restoran.svg" />
            </div>
            <label>Restoran</label>
            <p>
               Dari kacamata calon pelanggan, tampilan fisik dari sebuah restoran adalah yang pertama kali menarik perhatian
               untuk didatangi. Karenanya, kami siap menjadikan restoran Anda bukan hanya sebagai tempat bersantap namun juga kanvas yang memanjakan mata.
            </p>
         </div>
         <div class="business-hotel-box">
            <div class="business-hotel-box-img">
               <img src="/skin/frontend/smartwave/porto/images/icon-rumah.svg" />
            </div>
            <label>Rumah</label>
            <p>
               Tempat di mana seseorang dan keluarganya pulang dan tinggal sudah tentu memiliki nilai emosional tinggi. Sebuah kehormatan bagi kami bila diijinkan ikut
               andil dalam menjadikan keseharian Anda selalu berkesan.
            </p>
         </div>
      </div>
   </div>
   <div class="business-work">
      <h2>Our Works</h2>
      <div class="work-sliders" id="work-main">
         <div class="item">
            <div class="slider-work-main" id="work-inner">
               <div class="item">
                  <div class="slider-work-inner">
                     <img src="/skin/frontend/smartwave/porto/images/getcraft-new.png" />
                  </div>
               </div>
               <div class="item">
                  <div class="slider-work-inner">
                     <img src="/skin/frontend/smartwave/porto/images/getcraft-2.png" />
                  </div>
               </div>
               <div class="item">
                  <div class="slider-work-inner">
                     <img src="/skin/frontend/smartwave/porto/images/getcraft-3.png" />
                  </div>
               </div>
               <div class="item">
                  <div class="slider-work-inner">
                     <img src="/skin/frontend/smartwave/porto/images/getcraft-4.png" />
                  </div>
               </div>
               <div class="item">
                  <div class="slider-work-inner">
                     <img src="/skin/frontend/smartwave/porto/images/getcraft-5.png" />
                  </div>
               </div>
               <div class="item">
                  <div class="slider-work-inner">
                     <img src="/skin/frontend/smartwave/porto/images/getcraft-6.png" />
                  </div>
               </div>
               <div class="item">
                  <div class="slider-work-inner">
                     <img src="/skin/frontend/smartwave/porto/images/getcraft-7.png" />
                  </div>
               </div>
            </div>
            <div class="slider-work-content">
               <label> Getcraft</label>
               <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididnut
                  ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation
                  ullamco laboris nisi ut aliquip ex ea commodo consequat.
               </p>
            </div>
         </div>
         <div class="item">
            <div class="slider-work-main" id="work-gojek">
               <div class="item">
                  <div class="slider-work-inner">
                     <img src="/skin/frontend/smartwave/porto/images/gojek-new.png" />
                  </div>
               </div>
               <div class="item">
                  <div class="slider-work-inner">
                     <img src="/skin/frontend/smartwave/porto/images/gojek-2.png" />
                  </div>
               </div>
               <div class="item">
                  <div class="slider-work-inner">
                     <img src="/skin/frontend/smartwave/porto/images/gojek-3.png" />
                  </div>
               </div>
               <div class="item">
                  <div class="slider-work-inner">
                     <img src="/skin/frontend/smartwave/porto/images/gojek-2.png" />
                  </div>
               </div>
            </div>
            <div class="slider-work-content">
               <label>Gojek</label>
               <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididnut
                  ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation
                  ullamco laboris nisi ut aliquip ex ea commodo consequat.
               </p>
            </div>
         </div>
         <div class="item">
            <div class="slider-work-main" id="work-lewisandCarroll">
               <div class="item">
                  <div class="slider-work-inner">
                     <img src="/skin/frontend/smartwave/porto/images/lnc-new.png" />
                  </div>
               </div>
               <div class="item">
                  <div class="slider-work-inner">
                     <img src="/skin/frontend/smartwave/porto/images/lnc-2.png" />
                  </div>
               </div>
               <div class="item">
                  <div class="slider-work-inner">
                     <img src="/skin/frontend/smartwave/porto/images/lnc-3.png" />
                  </div>
               </div>
               <div class="item">
                  <div class="slider-work-inner">
                     <img src="/skin/frontend/smartwave/porto/images/gojek-2.png" />
                  </div>
               </div>
            </div>
            <div class="slider-work-content">
               <label>Lewis and Carroll</label>
               <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididnut
                  ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation
                  ullamco laboris nisi ut aliquip ex ea commodo consequat.
               </p>
            </div>
         </div>
         <div class="item">
            <div class="slider-work-main" id="work-Sunsetlimited">
               <div class="item">
                  <div class="slider-work-inner">
                     <img src="/skin/frontend/smartwave/porto/images/sunset-1.png" />
                  </div>
               </div>
               <div class="item">
                  <div class="slider-work-inner">
                     <img src="/skin/frontend/smartwave/porto/images/sunset-2.png" />
                  </div>
               </div>
               <div class="item">
                  <div class="slider-work-inner">
                     <img src="/skin/frontend/smartwave/porto/images/sunset-3.png" />
                  </div>
               </div>
               <div class="item">
                  <div class="slider-work-inner">
                     <img src="/skin/frontend/smartwave/porto/images/sunset-4.png" />
                  </div>
               </div>
            </div>
            <div class="slider-work-content">
               <label>Sunset Limited</label>
               <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididnut
                  ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation
                  ullamco laboris nisi ut aliquip ex ea commodo consequat.
               </p>
            </div>
         </div>
         <div class="item">
            <div class="slider-work-main" id="work-table">
               <div class="item">
                  <div class="slider-work-inner">
                     <img src="/skin/frontend/smartwave/porto/images/t6-1.png" />
                  </div>
               </div>
               <div class="item">
                  <div class="slider-work-inner">
                     <img src="/skin/frontend/smartwave/porto/images/t6-2.png" />
                  </div>
               </div>
               <div class="item">
                  <div class="slider-work-inner">
                     <img src="/skin/frontend/smartwave/porto/images/t6-3.png" />
                  </div>
               </div>
               <div class="item">
                  <div class="slider-work-inner">
                     <img src="/skin/frontend/smartwave/porto/images/sunset-4.png" />
                  </div>
               </div>
            </div>
            <div class="slider-work-content">
               <label>Table</label>
               <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididnut
                  ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation
                  ullamco laboris nisi ut aliquip ex ea commodo consequat.
               </p>
            </div>
         </div>
      </div>
   </div>
   <div class="business-testimonial-main">
      <h2>Testimonial</h2>
      <div id="business-testimonial" class="owl-carousel">
         <div class="item">
            <div class="testi-left">
               <div class="test-image-container">
                  <img src="/skin/frontend/smartwave/porto/images/slide-01-kantor.jpg" />
               </div>
               <p>
                  Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore
                  et dolore magna aliqua. ut enim ad minim veniam, quis nostrud exercitation.
               </p>
               <label>Nadiem Makarim, CEO Go-Jek</label>
            </div>
         </div>
         <div class="item">
            <div class="testi-left">
               <div class="test-image-container">
                  <img src="/skin/frontend/smartwave/porto/images/slide-01-kantor.jpg" />
               </div>
               <p>
                  Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore
                  et dolore magna aliqua. ut enim ad minim veniam, quis nostrud exercitation.
               </p>
               <label>Nadiem Makarim, CEO Go-Jek</label>
            </div>
         </div>
         <div class="item">
            <div class="testi-left">
               <div class="test-image-container">
                  <img src="/skin/frontend/smartwave/porto/images/slide-01-kantor.jpg" />
               </div>
               <p>
                  Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore
                  et dolore magna aliqua. ut enim ad minim veniam, quis nostrud exercitation.
               </p>
               <label>Nadiem Makarim, CEO Go-Jek</label>
            </div>
         </div>
         <div class="item">
            <div class="testi-left">
               <div class="test-image-container">
                  <img src="/skin/frontend/smartwave/porto/images/slide-01-kantor.jpg" />
               </div>
               <p>
                  Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore
                  et dolore magna aliqua. ut enim ad minim veniam, quis nostrud exercitation.
               </p>
               <label>Nadiem Makarim, CEO Go-Jek</label>
            </div>
         </div>
      </div>
   </div>
   <div class="why-fab ">
      <div class="why-fab-inner show-desktop">
         <h2>Mengapa Fabelio? Mengapa Tidak!</h2>
         <div class="why-fab-box">
            <div class="why-fab-box-left">
               <img src="/skin/frontend/smartwave/porto/images/why-fabelio-1.png" />
            </div>
            <div class="why-fab-box-right">
               <h3>Penyesuaian furniture tanpa biaya tambahan</h3>
               <p>Ingin memanfaatkan ruang kosong di bawah tangga denga rak kami? Atau butuh meja kerja dengan kapasitas 10 orang? Kami akan membuatkannya khusus untuk Anda, tanpa biaya tambahan sepeserpun! Karena tujuan kami adalah menghadirkan kualitas yang lebih lewat desain terbaik.</p>
            </div>
         </div>
         <div class="why-fab-box">
            <div class="why-fab-box-left">
               <img src="/skin/frontend/smartwave/porto/images/why-fabelio-2.png" />
            </div>
            <div class="why-fab-box-right">
               <h3>Pelayanan paripurna</h3>
               <p>Tim kami akan dengan denang hati melayani semua permintaan Anda, serta memastikan semuanya berjalan lancar dari sisi kualitas furnitur hingga ke tahap feed out interior.</p>
            </div>
         </div>
         <div class="why-fab-box">
            <div class="why-fab-box-left">
               <img src="/skin/frontend/smartwave/porto/images/why-fabelio-3.png" />
            </div>
            <div class="why-fab-box-right">
               <h3>Harga kompetitif</h3>
               <p>Kami memberi pelayanan serta kualitas maksimal dengan biaya yang bisa dipertanggungjawabkan. Kerjasama yang baik dengan supplier
                  dan kontraktor terpercaya memungkinkan kami mendapatkan hasil akhir yang sepadan dengan biaya yang dikeluarkan. 
               </p>
            </div>
         </div>
         <div class="why-fab-box">
            <div class="why-fab-box-left">
               <img src="/skin/frontend/smartwave/porto/images/why-fabelio-4.png" />
            </div>
            <div class="why-fab-box-right">
               <h3>Garansi 1 tahun</h3>
               <p>Kami memberi garansi selama 1 tahun penuh bila terjadi kesalahan pada proses produksi furnitur, termasuk bila terjadi kerusakan
                  atau patah. Ini berlaku untuk semua furnitur tanpa terkecuali.
               </p>
            </div>
         </div>
      </div>
      <div class="show-mobile">
         <h2>Mengapa Fabelio? <br>Mengapa Tidak!</h2>
         <div id="why-fab" >
            <div class="why-fab-box">
               <div class="why-fab-box-left">
                  <img src="/skin/frontend/smartwave/porto/images/why-fabelio-1.png" />
               </div>
               <div class="why-fab-box-right">
                  <h3>Penyesuaian furniture tanpa biaya tambahan</h3>
                  <p>Ingin memanfaatkan ruang kosong di bawah tangga denga rak kami? Atau butuh meja kerja dengan kapasitas 10 orang? Kami akan membuatkannya khusus untuk Anda, tanpa biaya tambahan sepeserpun! Karena tujuan kami adalah menghadirkan kualitas yang lebih lewat desain terbaik.</p>
               </div>
            </div>
            <div class="why-fab-box">
               <div class="why-fab-box-left">
                  <img src="/skin/frontend/smartwave/porto/images/why-fabelio-2.png" />
               </div>
               <div class="why-fab-box-right">
                  <h3>Pelayanan paripurna</h3>
                  <p>Tim kami akan dengan denang hati melayani semua permintaan Anda, serta memastikan semuanya berjalan lancar dari sisi kualitas furnitur hingga ke tahap feed out interior.</p>
               </div>
            </div>
            <div class="why-fab-box">
               <div class="why-fab-box-left">
                  <img src="/skin/frontend/smartwave/porto/images/why-fabelio-3.png" />
               </div>
               <div class="why-fab-box-right">
                  <h3>Harga kompetitif</h3>
                  <p>Kami memberi pelayanan serta kualitas maksimal dengan biaya yang bisa dipertanggungjawabkan. Kerjasama yang baik dengan supplier
                     dan kontraktor terpercaya memungkinkan kami mendapatkan hasil akhir yang sepadan dengan biaya yang dikeluarkan. 
                  </p>
               </div>
            </div>
            <div class="why-fab-box">
               <div class="why-fab-box-left">
                  <img src="/skin/frontend/smartwave/porto/images/why-fabelio-4.png" />
               </div>
               <div class="why-fab-box-right">
                  <h3>Garansi 1 tahun</h3>
                  <p>Kami memberi garansi selama 1 tahun penuh bila terjadi kesalahan pada proses produksi furnitur, termasuk bila terjadi kerusakan
                     atau patah. Ini berlaku untuk semua furnitur tanpa terkecuali.
                  </p>
               </div>
            </div>
         </div>
      </div>
      <div class="how-fab-work">
         <h2>Inilah Cara Kerja Kami</h2>
         <ul class="fab-timeline">
            <li>
               <div class="fab-timeline-img">
                  <img src="/skin/frontend/smartwave/porto/images/01-Perkenalan.png" />
               </div>
               <div class="fab-timeline-content">
                  <h3>Perkenalan</h3>
                  <label>Pembahasan Awal</label>
                  <label>Project Briefing</label>
                  <label>Perjanjain Kerjasama</label>
               </div>
            </li>
            <li>
               <div class="fab-timeline-img">
                  <img src="/skin/frontend/smartwave/porto/images/02-Desain.png" />
               </div>
               <div class="fab-timeline-content">
                  <h3>Desain</h3>
                  <label>Kunjungan Lokasi</label>
                  <label>Desain Interior</label>
                  <label>Penyesuaian Desain</label>
               </div>
            </li>
            <li>
               <div class="fab-timeline-img">
                  <img src="/skin/frontend/smartwave/porto/images/03-Pengerjaan.png" />
               </div>
               <div class="fab-timeline-content">
                  <h3>Pengerjaan</h3>
                  <label>Feed-out Interior</label>
                  <label>Produksi Furnitur</label>
                  <label>Quality Control</label>
               </div>
            </li>
            <li>
               <div class="fab-timeline-img">
                  <img src="/skin/frontend/smartwave/porto/images/04-Penyelesaian.png" />
               </div>
               <div class="fab-timeline-content">
                  <h3>Penyelesaian</h3>
                  <label>Pengiriman Furnitur</label>
                  <label>Penyelesaian Akhir</label>
                  <label>Layanan Purnajual</label>
               </div>
            </li>
         </ul>
      </div>
   </div>
   <div class="bus-sol">
      <div class="bus-sol-left">
         <h2>Kontak Tim Business Solution Kami</h2>
         <p>Kredibilitas kami menjamin kantor rumah Anda layak huni.</p>
         <p>Hubungi Sales Agent kami di 0812 1913 3310
            pertanyaan seputar jasa konsultasi kami.
         </p>
         <a href="javascript:void(0)" class="bus-sol-btn">Daftar Layhanan Konsultasi</a>
      </div>
      <div class="bus-sol-right">
         <img src="/skin/frontend/smartwave/porto/images/sales-agent.png" />
      </div>
   </div>
</div>
<script>
   jQuery(document).ready(function(){
   
   
   
   jQuery('.main').removeClass('container');
   
   
   
   
   
   jQuery("#main-slider").owlCarousel({
   
       autoPlay: 2000, //Set AutoPlay to 2 seconds
   
   pagination:false,
   
   navigation:false,
   
       items: 1,
   
       itemsDesktop: [1199, 1],
   
       itemsDesktopSmall: [979, 1],
   
       itemsMobile: [979, 1],
   
      navigationText:["<i class='icon-chevron-left'></i>","<i class='icon-chevron-right'></i>"]
   
   });  
   
   
   
   jQuery("#work-main").owlCarousel({
   
       autoPlay: false, 
   
   pagination:false,
   
   navigation:true,
   
       items: 1,
   
       itemsDesktop: [1199, 1],
   
       itemsDesktopSmall: [979, 1],
   
        itemsMobile: [979, 1],
   
       navText:true,
   
     navigationText: ["<img src='/skin/frontend/smartwave/porto/images/arrow-left.svg' />", "<img src='/skin/frontend/smartwave/porto/images/arrow-right.svg' />"]
   
   });  
   
         
   
         
   
          jQuery("#why-fab").owlCarousel({
   
       autoPlay: false, 
   
   pagination:false,
   
   navigation:true,
   
       items: 1,
   
       itemsDesktop: [1199, 1],
   
       itemsDesktopSmall: [979, 1],
   
        itemsMobile: [979, 1],
   
       
   
       
   
     navigationText: ["<img src='/skin/frontend/smartwave/porto/images/arrow-left.svg' />", "<img src='/skin/frontend/smartwave/porto/images/arrow-right.svg' />"]
   
   });  
   
         
   
   jQuery("#work-inner,#work-gojek,#work-lewisandCarroll,#work-Sunsetlimited,#work-table").owlCarousel({
   
       autoPlay: false, //Set AutoPlay to 3 seconds
   
   pagination:true,
   
   navigation:true,
   
       items: 1,
   
       itemsDesktop: [1199, 1],
   
       itemsDesktopSmall: [979, 1],
   
      itemsMobile: [979, 1],
   
      
   
       navigationText: ["<i class='fa fa-angle-left'>", "<i class='fa fa-angle-right'>"]
   
   });  
   
   
   
   jQuery("#business-testimonial").owlCarousel({
   
       autoPlay: false, 
   
   pagination:false,
   
   navigation:true,
   
       items: 2,
   
       itemsDesktop: [1199, 1],
   
       itemsDesktopSmall: [979, 1],
   
       itemsMobile: [979, 1],
   
       navigationText: ["<img src='/skin/frontend/smartwave/porto/images/arrow-left.svg' />", "<img src='/skin/frontend/smartwave/porto/images/arrow-right.svg' />"]
   
   });
   
   
   
   
   
   
   
   
   
   jQuery('.bus-sol-btn').click(function(){
   
   var topOffSet = jQuery('.business-form').offset().top;
   
   jQuery('html,body').animate({scrollTop: topOffSet - 70}, 600);
   
   });
   
   
   
   
   
   
   
   });
   
   
   
   
   
</script>