<?php $_product = $this->getProduct(); ?>
<?php $buttonTitle = $this->__('Add to Cart'); ?>
<?php if($_product->isSaleable()): ?>
    <div class="add-to-cart">
        <?php if(!$_product->isGrouped()): ?>
        <div class="qty-prod-li clearfix">
	<div class="hand-craft">
                <label><?php
                if($_product->getStockItem()->getQty()){
                    $DeliveryTime = $_product->getDeliveryTime();
                }else{
                     $DeliveryTime = $_product->getDeliverytimeBackorder();
                }
                $DeliveryTimeArray = explode(":", $DeliveryTime);
                $counter = count($DeliveryTimeArray);
                if ($counter > 1) { 
                    $DeliveryTimeNumberOnly = explode(" ", trim($DeliveryTimeArray[1]));
                    if(count($DeliveryTimeNumberOnly) > 1)
                    { 
                            if($DeliveryTimeNumberOnly[0] >= 11){echo '<label style="color:#f7941d;">Handcrafted Order</label>'; } else{echo '<label style="color:#00a249;">Ready Stock</label>'; }
                    }
                } else {
                    echo $DeliveryTimeArray[0];
                }
               
?>-</label>
 <?php /*               <span>Barang ini akan diproduksi dan dikirim dalam 
<span id="delivery-time-days-status"> 
<?php
if($_product->getStockItem()->getQty())
{
    if($DeliveryTimeNumberOnly[0] >= 3 && $DeliveryTimeNumberOnly[0] < 14) echo "<b>".$DeliveryTimeNumberOnly[0]." hari</b>";
    if($DeliveryTimeNumberOnly[0] >= 14 && $DeliveryTimeNumberOnly[0] < 19) echo "<b>2 minggu</b>";
    if($DeliveryTimeNumberOnly[0] >= 19 && $DeliveryTimeNumberOnly[0] < 26) echo "<b>3 minggu</b>";
    if($DeliveryTimeNumberOnly[0] >= 26 && $DeliveryTimeNumberOnly[0] < 33) echo "<b>4 minggu</b>";
    if($DeliveryTimeNumberOnly[0] >= 33 && $DeliveryTimeNumberOnly[0] < 40) echo "<b>5 minggu</b>";
    if($DeliveryTimeNumberOnly[0] >= 40 && $DeliveryTimeNumberOnly[0] < 47) echo "<b>6 minggu</b>";
    if($DeliveryTimeNumberOnly[0] >= 47 && $DeliveryTimeNumberOnly[0] < 54) echo "<b>7 minggu</b>";
    if($DeliveryTimeNumberOnly[0] >= 54) echo "<b>8-9 minggu</b>";
}
else
{
    $DeliveryTime = $_product->getDeliverytimeBackorder();
    $DeliveryTimeArray = explode(" ", $DeliveryTime);
    if($DeliveryTimeNumberOnly[0] >= 3 && $DeliveryTimeNumberOnly[0] < 14) echo "<b>".$DeliveryTimeNumberOnly[0]." hari</b>";
    if($DeliveryTimeNumberOnly[0] >= 14 && $DeliveryTimeNumberOnly[0] < 19) echo "<b>2 minggu</b>";
    if($DeliveryTimeNumberOnly[0] >= 19 && $DeliveryTimeNumberOnly[0] < 26) echo "<b>3 minggu</b>";
    if($DeliveryTimeNumberOnly[0] >= 26 && $DeliveryTimeNumberOnly[0] < 33) echo "<b>4 minggu</b>";
    if($DeliveryTimeNumberOnly[0] >= 33 && $DeliveryTimeNumberOnly[0] < 40) echo "<b>5 minggu</b>";
    if($DeliveryTimeNumberOnly[0] >= 40 && $DeliveryTimeNumberOnly[0] < 47) echo "<b>6 minggu</b>";
    if($DeliveryTimeNumberOnly[0] >= 47 && $DeliveryTimeNumberOnly[0] < 54) echo "<b>7 minggu</b>";
    if($DeliveryTimeNumberOnly[0] >= 54) echo "<b>8-9 minggu</b>";
}             
?></span>
</span>  /**/ ?>
<?php
/*** FAB-200 Start***************/
?>
               <span>
<?php
$deliveryDaysData=$this->getDeliveryDateOptions($DeliveryTimeNumberOnly[0]);
if($deliveryDaysData['deliveryDays'] >0){
	
	//echo " Delivery TimeNumber : ".$DeliveryTimeNumberOnly[0]." Delivery DateWas : ".$toDate." totalSaturdays : ".$totalSaturdays." totalSundays : ".$totalSundays." CutOffDay : ".$cutoffDay." Now DeliverDate : ".$deliveryDate;
	setlocale(LC_TIME, 'IND');
	$stringDeliveryDate=strftime('%d %B', strtotime($deliveryDaysData['deliveryDate']));
	$dataStringForDate=$this->__($stringDeliveryDate);
		
	if($_product->getStockItem()->getQty()){
		if($deliveryDaysData['deliveryDays'] <= 10){
			echo 'Ingin barang ini sampai pada <b>'.$dataStringForDate.'</b>? Pesan barang ini dalam waktu <span id="countdown" class="timer"></span>!';
		}else{
			echo "Barang ini akan dikirim pada tanggal <b>".$dataStringForDate."</b>.";
		}
		// echo "want this stuff up on <b>".$dataStringForDate."</b> ? This item message within 10 hours 22 minutes !";
    
	}else{
		$DeliveryTime = $_product->getDeliverytimeBackorder();
		$DeliveryTimeArray = explode(" ", $DeliveryTime);
		if($deliveryDaysData['deliveryDays'] <= 10){
			echo 'Ingin barang ini sampai pada <b>'.$dataStringForDate.'</b>? Pesan barang ini dalam waktu <span id="countdown" class="timer"></span>!';
		}else{
			echo "Barang ini akan dikirim pada tanggal <b>".$dataStringForDate."</b>.";
		}
		
	}     
}
        
?>

</span>
<?php
/*** FAB-200 End***************/
?>





            </div>
          <label for="qty" class="pull-left qty-lbl"><?php echo $this->__('Qty:') ?></label>
          <div class="qty-holder pull-right">
            <a href="javascript:void(0)" class="table_qty_dec">-</a>
              <input type="text" name="qty" id="qty" maxlength="12" value="<?php echo $this->getProductDefaultQty() * 1 ?>" title="<?php echo $this->__('Qty') ?>" class="input-text qty" />
            <a href="javascript:void(0)" class="table_qty_inc">+</a>
          </div>
        </div>
        <?php endif; ?>
        <div class="add-to-btn-wrap">
          <button type="button" title="<?php echo $buttonTitle ?>" class="add-to-cart-btn fab-btn fab-btn-primary" onclick="productAddToCartForm.submit(this)">
            <i class="icon-cart"></i><?php echo $this->__('Beli Sekarang'); ?>
          </button>
          <span id='ajax_loader' style='display:none'><i class="ajax-loader small animate-spin"></i></span>
          <?php echo $this->getChildHtml('', true, true) ?>
        </div>
    </div>
<?php endif; ?>
<?php
/*** FAB-200 Start***************/
?>
<script>
function startTimer(duration, display) {
    var timer = duration, hours, minutes, seconds;
    setInterval(function () {
        hours = parseInt(timer / 3600, 10);
		var minutesLeft = Math.floor((timer) - (hours*3600));
		minutes = Math.floor(minutesLeft/60);
		seconds = timer % 60;
		hours = hours < 10 ? "0" + hours : hours;
		minutes = minutes < 10 ? "0" + minutes : minutes;
        seconds = seconds < 10 ? "0" + seconds : seconds;
        //display.textContent = hours + ":" + minutes + ":" + seconds;
		display.textContent = hours + " jam " + minutes + " menit";
        if (--timer < 0) {
            timer = duration;
        }
    }, 1000);
}

jQuery(document).ready(function(){    
	var timer = <?php echo $deliveryDaysData['differenceInSeconds']; ?>,
        display = document.querySelector('#countdown');
		
    startTimer(timer, display);
});
</script>
<?php
/*** FAB-200 End***************/
?>