<?php $_product = $this->getProduct(); ?>
<?php $buttonTitle = $this->__('Add to Cart'); ?>
<?php if($_product->isSaleable()): ?>
    <div class="add-to-cart">
        <?php if(!$_product->isGrouped()): ?>
        <div class="qty-prod-li clearfix">
          <label for="qty" class="pull-left qty-lbl"><?php echo $this->__('Qty:') ?></label>
          <div class="qty-holder pull-right">
            <a href="javascript:void(0)" class="table_qty_dec">-</a>
              <input type="text" name="qty" id="qty" maxlength="12" value="<?php echo $this->getProductDefaultQty() * 1 ?>" title="<?php echo $this->__('Qty') ?>" class="input-text qty" />
            <a href="javascript:void(0)" class="table_qty_inc">+</a>
          </div>
        </div>
        <?php endif; ?>
        <div class="add-to-btn-wrap">
          <button type="button" title="<?php echo $buttonTitle ?>" class="add-to-cart-btn fab-btn fab-btn-primary" onclick="productAddToCartForm.submit(this)">
            <i class="icon-cart"></i><?php echo $this->__('Beli Sekarang'); ?>
          </button>
          <span id='ajax_loader' style='display:none'><i class="ajax-loader small animate-spin"></i></span>
          <?php echo $this->getChildHtml('', true, true) ?>
        </div>
    </div>
<?php endif; ?>
<?php
$session = Mage::getSingleton("core/session");
$cartData = $session->getData("sessionCartDataArray");
$productSku = $_product->getSku(); 
$product = Mage::getModel('catalog/product')->loadByAttribute('sku', $productSku);
$categories = $product->getCategoryIds();
?>
<script type="text/javascript">
jQuery(function($){ 
   jQuery('.add-to-cart-btn').on('click', function(e){
       if(productAddToCartForm.validator.validate()){
//alert(products.length);
var products = jQuery.parseJSON('<?php $session = Mage::getSingleton("core/session"); $cartData = $session->getData("sessionCartDataArray"); echo json_encode($cartData) ?>');      
//console.log(products);
var current_product =     
    [{
     'id': '<?php echo $_product->getId(); ?>',
     'categoryId': '<?php echo Mage::getModel('catalog/category')->load($categories[0])->getId(); ?>',
     'transactionId': '',
     'price': '<?php echo Mage::helper('core')->currency($product->getPrice(), true, false); ?>',
     'quantity': jQuery('#qty').val(),
     'name': '<?php echo $_product->getName(); ?>',
     'brandName': '<?php echo $product->getAttributeText('manufacturer'); ?>',
     'desc': '',
     'imageUrl': '<?php echo Mage::helper('catalog/image')->init($product, 'thumbnail') ?>',
     'link': '<?php echo $product->getProductUrl() ?>' 
     }];
var product_already_exist_flag = 0;

if(products.length > 0)
{
for(i=0;i<products.length;i++)
{
if(products[i]['id']==current_product[0]['id'])
{ //alert('update product');
var updated_qty = parseInt(products[i]['quantity']) + parseInt(current_product[0]['quantity']);
products[i]['quantity'] = updated_qty.toString();
product_already_exist_flag = 1;
break;
}
}
}
if(product_already_exist_flag==0 && products.length > 0){ products.push(current_product[0]);}
if(product_already_exist_flag==0 && products.length == 0){ products = current_product;}
console.log(products); 
ematics("log", "product", "cart", products);
       }
     });
  });
</script>
