<?php $id = $this->getIdBox() ?>
<?php $chart = Mage::getModel('inventorydashboard/items')->load($id) ?>
<?php     
    $resource = Mage::getSingleton('core/resource');        
    $readConnection = $resource->getConnection('core_read');
    $results = '';
    $sql = 'SELECT `supplier_id`,count(`supplier_id`) as `total_time` FROM '.$resource->getTableName('erp_inventory_purchase_order').' group by `supplier_id`';     
    $results = $readConnection->query($sql);
    $supplierPurchase = array();
    if($results){
        foreach($results as $result){            
            $supplierPurchase[$result['supplier_id']] = $result['total_time'];
        }
    }
    $supplierCollection = Mage::getModel('inventorypurchasing/supplier')->getCollection();
    $series = '';
    $i = 0;    
    foreach($supplierCollection as $supplier){
        $totalTime = 0;
        if(isset($supplierPurchase[$supplier->getId()]))
            $totalTime = $supplierPurchase[$supplier->getId()];
        if($i!=0)
            $series .= ',';
        $series .= '[\''.$supplier->getSupplierName().'('.$totalTime.' order(s))\','.$totalTime.']';
        $i++;
    }
?>
                            
<script type="text/javascript">
$(function () {
    $_('#<?php echo $id ?>').highcharts({
        chart: {
            plotBackgroundColor: null,
            plotBorderWidth: 1,//null,
            plotShadow: false
        },
        title: {
            text: '<?php echo $chart->getName() ?>',
            x: -20 //center
        },        
        tooltip: {
            pointFormat: '{series.name}: <b>{point.percentage:.1f} %</b>'
        },
        plotOptions: {
            pie: {
                allowPointSelect: true,
                cursor: 'pointer',
                dataLabels: {
                    enabled: true,
                    format: '<b>{point.name}</b>: {point.percentage:.1f} %',
                    style: {
                        color: (Highcharts.theme && Highcharts.theme.contrastTextColor) || 'black'
                    }
                }
            }
        },
        series: [{
            type: 'pie',
            name: '<?php echo $this->__('No. of purchase orders') ?>',
            data: [                
                <?php echo $series ?>
            ]
        }]
    });
});
</script>
<?php if (Mage::helper('core')->isModuleEnabled('Magestore_Inventoryreports')):?>
<span style="width: 100%; float: right;">
        <a style="text-decoration: none; cursor: pointer; float:right; margin: 10px 10px 0 0" onclick="window.open('<?php echo Mage::helper("adminhtml")->getUrl("inventoryreportsadmin/adminhtml_supplier/inventorybysupplier", array("_secure" => Mage::app()->getStore()->isCurrentlySecure()));?>', '_blank', 'scrollbars=yes, resizable=yes, width=1000, height=600, top=50, left=300')"/><?php echo $this->__('More details')?></a>
    </span>
<?php endif;?>
<div id="<?php echo $id ?>" style="min-width: 310px; max-height: 400px;  margin: 30px auto 0;"></div>