<?php $rates = $this->getRates(); ?>
<div class="my-account">
    <div class="page-title">
        <h1><?php echo Mage::helper('marketplace')->__('My rates'); ?></h1>
    </div>
    <div class="box-account box-recent">
    	<form method="POST">
	    <table class="data-table orders" id="my-rates-table">
    	<colgroup>
            <col width="50%">
    		<col width="50%">
    	</colgroup>
	    <thead>
	        <tr class="first last">
	            <th><?php echo Mage::helper('marketplace')->__('Supplier Name'); ?></th>
	            <th><?php echo Mage::helper('marketplace')->__('Rate'); ?></th>
	        </tr>
	        </thead>
	        <tbody>
			<?php if(count($rates) > 0) : ?>
				<?php foreach($rates AS $rate): ?>
					<?php $vendor = Mage::getModel('customer/customer')->load($rate->getSupplierId()); ?>
	            	<tr class="last">		
	            	    <td><?php echo $this->escapeHtml($vendor->getFirstname() . ' ' . $vendor->getLastname()); ?></td>
	        	        <td class="last rate-list">
							<input type="radio" name="ratings[<?php echo $rate->getId() ?>]" value="1" class="radio" <?php echo $rate->getRate() == 1 ? 'checked="checked" ' : '' ?>title="1" id="rate-<?php echo $rate->getId() ?>-1"/><label
                                for="rate-<?php echo $rate->getId() ?>-1">1</label>
							<input type="radio" name="ratings[<?php echo $rate->getId() ?>]" value="2" class="radio" <?php echo $rate->getRate() == 2 ? 'checked="checked" ' : '' ?>title="2" id="rate-<?php echo $rate->getId() ?>-2"/><label
                                for="rate-<?php echo $rate->getId() ?>-2">2</label>
							<input type="radio" name="ratings[<?php echo $rate->getId() ?>]" value="3" class="radio" <?php echo $rate->getRate() == 3 ? 'checked="checked" ' : '' ?>title="3" id="rate-<?php echo $rate->getId() ?>-3"/><label
                                for="rate-<?php echo $rate->getId() ?>-3">3</label>
							<input type="radio" name="ratings[<?php echo $rate->getId() ?>]" value="4" class="radio" <?php echo $rate->getRate() == 4 ? 'checked="checked" ' : '' ?>title="4" id="rate-<?php echo $rate->getId() ?>-4"/><label
                                for="rate-<?php echo $rate->getId() ?>-4">4</label>
							<input type="radio" name="ratings[<?php echo $rate->getId() ?>]" value="5" class="radio" <?php echo $rate->getRate() == 5 ? 'checked="checked" ' : '' ?>title="5" id="rate-<?php echo $rate->getId() ?>-5"/><label
                                for="rate-<?php echo $rate->getId() ?>-5">5</label>
	        	        </td>
	       	    </tr>
            	<?php endforeach; ?>
			<?php else : ?>
				<?php echo Mage::helper('marketplace')->__("No rates"); ?>
			<?php endif; ?>
	        </tbody>
	    </table>
	    <?php if(count($rates) > 0) : ?>
		    <div class="buttons-set">
		        <input type="submit" class="button">
	    	</div>
	    <?php endif; ?>
	    </form>
	</div>
</div>