<?php
$helper = Mage::helper("fabmod_fbpixel");
if (!$helper->isFbPxEnabled()) {
  return;
}
$_product = Mage::registry('current_product');
$categories = $_product->getCategoryIds();
?>
<script>
function fabmodFbpixelAddToCart(){
  fbq('track', 'AddToCart', {
    content_name     : '<?php echo $_product->getName(); ?>',
    content_category : '<?php echo Mage::getModel('catalog/category')->load($categories[0])->getName(); ?>',
    content_ids      : ['<?php echo $_product->getId(); ?>'],
    content_type     : 'product',
    value            : <?php echo $_product->getFinalPrice(); ?>,
    currency         : '<?php echo Mage::app()->getStore()->getCurrentCurrencyCode(); ?>'
  });  
}
jQuery(function($){
  $('.add-to-cart-btn').on('click', function(e){
    if(productAddToCartForm.validator.validate()){
      fabmodFbpixelAddToCart();
    }
  });
});
</script>
