<?php
/**
 * MagPleasure Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.magpleasure.com/LICENSE.txt
 *
 * @category   Magpleasure
 * @package    Magpleasure_Filesystem
 * @copyright  Copyright (c) 2011 Magpleasure Co. (http://www.magpleasure.com)
 * @license    http://www.magpleasure.com/LICENSE.txt
 */
?>

<div class="file-tree-wrapper">
    <div class="file-tree" id="file_tree"></div>
</div>

<script type="text/javascript">        
    jQuery(document).ready( function() {
        jQuery('#file_tree').fileTree({
            root: '<?php echo Mage::getBaseDir(); ?>/',
            script: '<?php echo $this->getUrl('filesystem/adminhtml_filesystem/tree', array('isAjax'=> true, 'form_key'=>$this->getFormKey())) ?>',
            expandSpeed: 200,
            collapseSpeed: 200
        }, function(file) {            
            var url = '<?php echo $this->getUrl("filesystem/adminhtml_filesystem/load", array("fn"=>"{{filename}}")) ?>';            
            openFile(url, file);
        });
    });
</script>