<?php
/**
 * Custom tab template
 */

?>


<?php
    $product_id = Mage::registry('current_product')->getId();
    $_product= Mage::getModel('catalog/product')->load($product_id);
    //var_dump($_product);
    $sku = $_product->getSku();
    //$matrixrate=Mage:Helper();
    $matrixrate_helper = Mage::helper('matrixrate');
    //var_dump($matrixrate_helper);
    $sku_data = $matrixrate_helper->get_sku_data($sku);
    //echo "<pre>"; print_r($sku_data); echo "</pre>";
?>

<div class="entry-edit-head">
    <h4 class="icon-head head-edit-form fieldset-legend">Shipping Information</h4>
</div>

<div class="fieldset fieldset-wide" id="group_fields7">
    <div class="hor-scroll">
        <table cellspacing="0" class="form-list">
            <tbody>
                
    <tr>
            <td class="label"><label for="fee_enabled">Fee Enabled</label></td>
            <td class="value">
                <input type="radio" name="fee_enabled" value="1" <?php if($sku_data['0']['express_fee_enabled']==1):?>checked="checked"<?php endif; ?> /> <label for="enabled">Enabled</label>
 <input type="radio" name="fee_enabled" value="0" <?php if($sku_data['0']['express_fee_enabled']==0):?>checked="checked"<?php endif; ?>/> <label for="disabled">Disabled</label>
            </td>
            <td class="scope-label"><span class="nobr"></span></td>
    </tr>
    
    <tr>
            <td class="label"><label for="express_number_of_days">Express number of days</label></td>
            <td class="value">
                <input type = "text" class="required-entry input-text required-entry" name="express_number_of_days" value="<?php echo $sku_data['0']['express_number_of_days']; ?>" id="express_number_of_days" />
            </td>
            <td class="scope-label"><span class="nobr"></span></td>
    </tr>
    
     <tr>
            <td class="label"><label for="express_fees">Express fees</label></td>
            <td class="value">
                <input type = "text" class="required-entry input-text required-entry" name="express_fees" value="<?php echo $sku_data['0']['price']; ?>" id="express_number_of_days" />
            </td>
            <td class="scope-label"><span class="nobr"></span></td>
    </tr>
    
    <tr>
            <td class="label"><label for="standard_number_of_days">Standard number of days</label></td>
            <td class="value">
                <input type = "text" name="standard_number_of_days" class="required-entry input-text required-entry" value="<?php echo $sku_data['1']['standard_number_of_days']; ?>" id="express_number_of_days" />
            </td>
            <td class="scope-label"><span class="nobr"></span></td>
    </tr>
    
    
    <tr>
            <td class="label"><label for="standard_fees">Standard fees</label></td>
            <td class="value">
                <input type = "text" name="standard_fees" class="required-entry input-text required-entry" value="<?php echo $sku_data['1']['price']; ?>" id="express_number_of_days" />
            </td>
            <td class="scope-label"><span class="nobr"></span></td>
    </tr>
    <tr>
           
            <td class="scope-label"><input type="hidden" name="sku" value="<?php echo $sku;  ?>" /><span class="nobr"></span></td>
    </tr>
    
            </tbody>
        </table>
    </div>
</div>
