<div class="entry-edit">
    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->__('Select time to create delivery') ?></h4>
    </div>
    <div id="" class="fieldset ">
        <table cellspacing="0" class="form-list">
            <tbody>
                <tr>               
                    <td class="value">
                        <?php $create_at = Mage::getModel('admin/session')->getData('delivery_create_at'); ?>
                        <input type="text" style="width:110px !important;" class="required-entry input-text validate-date" value="<?=$create_at?>" id="delivery_date" name="delivery_date"> 
                        <img style="" title="Select Date" id="delivery_date_trig" class="v-middle" alt="" src="<?php echo $this->getSkinUrl('images/grid-cal.gif') ?>">
                    </td>
                </tr>
            </tbody>
        </table>

        <script type="text/javascript">
            //&lt;![CDATA[          
            Calendar.setup({
                            inputField: 'delivery_date',
                            ifFormat: '%Y-%m-%d',
                            showsTime: false,
                            electric: false,
                            button: 'delivery_date_trig',
                            singleClick: true,
                            disableFunc: function(date) {
                                var today = new Date();
                                var check = false;    
                                //check closed day
                                if (date.getFullYear() > today.getFullYear()) {
                                    return true;
                                } else if (date.getMonth() > today.getMonth() && date.getFullYear() >= today.getFullYear()) {
                                    return true;
                                } else if (date.getDate() > today.getDate() && date.getMonth() >= today.getMonth() && date.getFullYear() >= today.getFullYear()) {
                                    return true;
                                }
                                if (today.getDate() == date.getDate()) {
                                    return false;
                                }
                            }
                            
                        });                        
                   
            //]]&gt;
        </script>
    </div>
</div>