<div class="entry-edit">
    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->__('Select Time to Create Return Order') ?></h4>
    </div>
    <div id="" class="fieldset ">
        <div style="float:left;width:30%">

            <table cellspacing="0" class="form-list">
                <tbody>
                    <tr>               
                        <td class="value">
                             <?php $time = Mage::getModel('admin/session')->getData('returnorder_create_at'); ?>
                            <input type="text" style="width:110px !important;" class="required-entry input-text validate-date" value="<?=$time ?>" id="return_date" name="return_date"> 
                            <img style="" title="Select Date" id="delivery_date_trig" class="v-middle" alt="" src="<?php echo $this->getSkinUrl('images/grid-cal.gif') ?>">
                        </td>
                    </tr>
                </tbody>
            </table>


            <script type="text/javascript">
                //&lt;![CDATA[
               Calendar.setup({
                            inputField: 'return_date',
                            ifFormat: '%Y-%m-%d',
                            showsTime: false,
                            electric: false,
                            button: 'delivery_date_trig',
                            singleClick: true,
                            disableFunc: function(date) {
                                var today = new Date();
                                var check = false;    
                                //check closed day
                                if (date.getFullYear() > today.getFullYear()) {
                                    return true;
                                } else if (date.getMonth() > today.getMonth() && date.getFullYear() >= today.getFullYear()) {
                                    return true;
                                } else if (date.getDate() > today.getDate() && date.getMonth() >= today.getMonth() && date.getFullYear() >= today.getFullYear()) {
                                    return true;
                                }
                                if (today.getDate() == date.getDate()) {
                                    return false;
                                }
                            }
                            
                        });            
                //]]&gt;
            </script>
        </div>
        <div style="float:left;">
            <lable for="return-order"><strong><?php echo $this->__('Reason(s) for returning order:') ?></strong><span class="required">*</span></lable>
            <br />
            <?php $reason = Mage::getModel('admin/session')->getData('returnorder_reason'); ?>
            <textarea id="reason" name="reason" title="<?php echo $this->__('Reason(s) to return order') ?>" style="width:350px; height:50px;" rows="2" cols="15" class="required-entry  textarea" ><?php echo $reason?></textarea>               
        </div>
        <div class="clear"></div>
    </div>
</div>