<?php
/**
 * Magmodules.eu
 * http://www.magmodules.eu
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to info@magmodules.eu so we can send you a copy immediately.
 *
 * @category    Magmodules
 * @package     Magmodules_Ordershare
 * @author      Magmodules <info@magmodules.eu)
 * @copyright   Copyright (c) 2013 (http://www.magmodules.eu)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>


<?php if($this->getEnabled()): ?>

	<div id="fb-root"></div>
	<!--<script>(function(d, s, id) {
	  var js, fjs = d.getElementsByTagName(s)[0];
	  if (d.getElementById(id)) return;
	  js = d.createElement(s); js.id = id;
	  js.src = "//connect.facebook.net/en_US/all.js#xfbml=1";
	  fjs.parentNode.insertBefore(js, fjs);
	}(document, 'script', 'facebook-jssdk'));</script>-->

	<h2 class="sub-title"><?php echo $this->__('Share your order on social media!'); ?></h2>
	
	<?php
                
		// Get the product IDs from last order
                $_helper = $this->helper('catalog/output');
		$order_id = Mage::getSingleton('checkout/session')->getLastRealOrderId();
		$order = Mage::getModel('sales/order')->loadByIncrementId($order_id);
                
                
               
                
		$items = $order->getAllVisibleItems();		
		foreach ($items as $item):
			
			// Load the product & image
                        $productId = $item->getProductId();
			$_product = Mage::getModel('catalog/product')->load($item->getProductId());
                        $productName = $_product->getName();
                        $productTitle = $_product->getName();
                        $productType = $_product->getTypeID();
                        
                        # Get parent id of product
                        $arrayOfParentIds =  Mage::getSingleton("catalog/product_type_configurable")->getParentIdsByChild($productId);
                        # Get product url of parent (configurable) product if exists
                        if(count($arrayOfParentIds) > 0){
                            $parentId = $arrayOfParentIds[0];
                            $_parent_product = Mage::getModel('catalog/product')->load($parentId);
                            $productUrl = $_parent_product->getProductUrl();
                            $attributeSetModel = Mage::getModel("eav/entity_attribute_set");
                            $attributeSetModel->load($_parent_product->getAttributeSetId()); // $product is your product object
                            $attributeSetName = $attributeSetModel->getAttributeSetName(); 
                            //$productName = $productName." - ".$attributeSetName;
                            $productName = str_replace('(', '', $productName);
                            $productName = str_replace(')', '', $productName);
                            
                            }else{
                                $productUrl = $_product->getProductUrl();
                            }
                
			$_img = '<img src="'.$this->helper('catalog/image')->init($_product, 'image')->resize(150).'" alt="'.$this->htmlEscape($this->getImageLabel()).'" title="'.$this->htmlEscape($this->getImageLabel()).'" />'; 
                        preg_replace('/[^A-Za-z0-9\-]/', '', $productName);
			// Echo products
			echo '<div class="share"><h3>' . $productTitle . '</h3>'; 
			echo $_img;
			echo '<div class="buttons">';
                        ?>
			<!-- // Twitter -->
<a href="javascript:popWin('http://twitter.com/home/?status=<?php echo urlencode($productName . ' (' . $productUrl . ')'); ?>', 'twitter', 'width=640,height=480,left=0,top=0,location=no,status=yes,scrollbars=yes,resizable=yes');" title="<?php echo $this->__('Tweet') ?>"><img width="105px" height="48px" src="<?php echo Mage::getBaseUrl()."skin/frontend/smartwave/porto/images/tweetbutton.png";?>" /></a>
<!-- // Facebook -->
<a href="javascript:popWin('https://www.facebook.com/sharer/sharer.php?u=<?php echo urlencode($productUrl); ?>&t=<?php echo urlencode($productName); ?>', 'facebook', 'width=640,height=480,left=0,top=0,location=no,status=yes,scrollbars=yes,resizable=yes');" title="<?php echo $this->__('Share on Facebook') ?>"><img  src="<?php echo Mage::getBaseUrl()."skin/frontend/smartwave/porto/images/facebookbutton.jpg";?>" /></a>
                        <?php
			echo '</div></div>';
			
		endforeach; 
	?>	
	
	<!--<script src="http://platform.twitter.com/widgets.js" type="text/javascript"></script>
	<script src="http://static.ak.fbcdn.net/connect.php/js/FB.Share" type="text/javascript"></script>-->
		
<?php endif; ?>