<?php
/**
 * Magmodules.eu
 * http://www.magmodules.eu
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to info@magmodules.eu so we can send you a copy immediately.
 *
 * @category    Magmodules
 * @package     Magmodules_Ordershare
 * @author      Magmodules <info@magmodules.eu)
 * @copyright   Copyright (c) 2013 (http://www.magmodules.eu)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>


<?php if($this->getEnabled()): ?>

	<div id="fb-root"></div>
	<script>(function(d, s, id) {
	  var js, fjs = d.getElementsByTagName(s)[0];
	  if (d.getElementById(id)) return;
	  js = d.createElement(s); js.id = id;
	  js.src = "//connect.facebook.net/en_US/all.js#xfbml=1";
	  fjs.parentNode.insertBefore(js, fjs);
	}(document, 'script', 'facebook-jssdk'));</script>

	<h2 class="sub-title"><?php echo $this->__('Share your order on social media!'); ?></h2>
	
	<?php
		// Get the product IDs from last order
		$order_id = Mage::getSingleton('checkout/session')->getLastRealOrderId();
		$order = Mage::getModel('sales/order')->loadByIncrementId($order_id);
		$items = $order->getAllVisibleItems();		
		foreach ($items as $item):
			
			// Load the product & image
			$_product = Mage::getModel('catalog/product')->load($item->getProductId());
			$_img = '<img src="'.$this->helper('catalog/image')->init($_product, 'image')->resize(150).'" alt="'.$this->htmlEscape($this->getImageLabel()).'" title="'.$this->htmlEscape($this->getImageLabel()).'" />'; 
	
			// Echo products
			echo '<div class="share"><h3>' . $_product->getName() . '</h3>'; 
			echo $_img;
			echo '<div class="buttons">';
			echo $this->getTwitterImg($_product); 
			echo $this->getFacebookImg($_product); 
			echo '</div></div>';
			
		endforeach; 
	?>	
	
	<script src="http://platform.twitter.com/widgets.js" type="text/javascript"></script>
	<script src="http://static.ak.fbcdn.net/connect.php/js/FB.Share" type="text/javascript"></script>
		
<?php endif; ?>