<?php
/**
 Made by Smartwave.
 */
?>
<?php
    $store = Mage::app()->getStore();
    $code  = $store->getCode();
    $popup = Mage::getStoreConfig('porto_settings/newsletter_popup',$code);
?>
<script type="text/javascript">
jQuery(function($) {
    var check_cookie = $.cookie('newsletter_popup');
    if(check_cookie == null || check_cookie == 'shown') {
        beginNewsletterForm();
    }
    $('#newsletter_popup_dont_show_again').on('change', function(){
        if($(this).length){        
            var check_cookie = $.cookie('newsletter_popup');
            if(check_cookie == null || check_cookie == 'shown') {
                $.cookie('newsletter_popup','dontshowitagain', { expires: 7 });
            }
            else
            {
                $.cookie('newsletter_popup','shown', { expires: 7 });
                //beginNewsletterForm();
            }
        } else {
            $.cookie('newsletter_popup','shown', { expires: 7 });
        }
    }); 
});

function beginNewsletterForm() {
    jQuery.fancybox({
        'padding': '0px',
        'showCloseButton': false,
        'autoScale': true,
        'transitionIn': 'fade',
        'transitionOut': 'fade',
        'type': 'inline',
        'href': '#newsletter_popup',
        'onComplete': function() {
            $.cookie('newsletter_popup', 'shown', { expires: 7 });
        },
        'tpl': { 
            closeBtn: '<a title="Close" class="fancybox-item fancybox-close fancybox-newsletter-close" href="javascript:;"></a>' 
            //closeBtn: false
        },
        'afterClose': function(){
            jQuery.cookie('newsletter_popup','dontshowitagain', { expires: 7 });
        }
    });
    jQuery('#newsletter_popup').trigger('click');
}

</script>
<style type="text/css">
<?php
    if($popup["newsletter_custom_style"]){
        echo $popup["newsletter_custom_style"];
    }
?>
#newsletter_popup{
<?php
    if($popup["newsletter_width"]){
        echo "width:".$popup["newsletter_width"].";";
    }
    if($popup["newsletter_height"]){
        echo "height:".$popup["newsletter_height"].";";
    }
    if($popup["newsletter_bg_color"]){
        echo "background-color:".$popup["newsletter_bg_color"].";";
    }
    if(isset($popup["newsletter_bg_image"]) && $popup["newsletter_bg_image"]){
?>
    background-image:url(<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA)."porto/newsletter_popup/".$popup['newsletter_bg_image'];?>);
    background-size: cover;
    border: none;
<?php
    }
?>
}
#newsletter_popup form {
  float: right;
  background-color: #f2f2f2;
  padding: 20px;
  box-shadow: 1px 1px 10px #999;
}
</style>
<div class="block block-subscribe" id="newsletter_popup">
    <form action="<?php echo $this->getFormActionUrl() ?>" method="post" id="newsletter-popup-validate-detail" onsubmit="setNewsletterCookie()">
        <div class="block-content">
            <?php
                if($popup["show_logo"]){
            ?>
                    <img src="<?php echo $this->getSkinUrl($popup["show_logo"]); ?>" alt="" />
            <?php
                }
            ?>
            <?php echo $popup['newsletter_content']; ?>
            <div class="nl-icons clearfix">
              <div class="nl-icon">
                <div class="nl-icon-img">
                  <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA)."porto/newsletter_popup/icons/nl-pop-icon1.png" ?>" style="margin-top: 6px;">
                </div>
                <div class="nl-text">Produk<br>Terbaru</div>
              </div>
              <div class="nl-icon">
                <div class="nl-icon-img">
                  <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA)."porto/newsletter_popup/icons/nl-pop-icon2.png"?>" style="margin-top: 11px;">
                </div>
                <div class="nl-text">Promo<br>Menarik</div>
              </div>
              <div class="nl-icon">
                <div class="nl-icon-img">
                  <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA)."porto/newsletter_popup/icons/nl-pop-icon3.png"?>">
                </div>
                <div class="nl-text">Inspirasi<br>Rumah</div>
              </div>
            </div>
            <div>
              <input type="text" name="email" id="newsletter_popup_email" title="<?php echo $this->__('Sign up for our newsletter') ?>" class="input-text required-entry validate-email" placeholder="<?php echo $this->__("Masukkan alamat email Anda"); ?>" />
            </div>
            <p>
              <button type="submit" title="<?php echo $this->__('Go!') ?>" class="fab-btn fab-btn-primary">Dapatkan voucher Rp 100.000</button>
            </p>
            <div class="subscribe-bottom">
                <input type="checkbox" id="newsletter_popup_dont_show_again"/>
                <label for="newsletter_popup_dont_show_again"><?php echo $this->__("Don't show this popup again"); ?></label>
            </div>
        </div>
    </form>
    <div class="clearer"></div>
    <script type="text/javascript">
    //<![CDATA[
        var newsletterpopupSubscriberFormDetail = new VarienForm('newsletter-popup-validate-detail');
        document.getElementById("newsletter-popup-validate-detail").onsubmit=function(){
            jQuery.cookie('newsletter_popup','dontshowitagain');
        }
    //]]>
    </script>
</div>
