<?php
$warehouseHistoryId = $this->getRequest()->getParam('warehouseHistoryId');
$warehouseHistory = $this->getWarehouseHistory($warehouseHistoryId);
$warehouseHistoryContent = $this->getWarehoueContentByHistoryId($warehouseHistoryId);
?>
<div class="content-header">
    <h3 class="icon-head head-adminhtml-warehouse"><?php echo $this->__('CHANGE HISTORY') ?></h3>
</div>
<div>
    <?php echo $this->__('Action Owner: ') . '<strong>' . $warehouseHistory->getCreateBy() . '</strong>'; ?>
    <br />
    <?php echo $this->__('Time Stamp: ') . '<strong>' . date('Y-m-d H:i:s', Mage::getModel('core/date')->timestamp($warehouseHistory->getTimeStamp())) . '</strong>'; ?>
</div>
<br />
<?php if (count($warehouseHistoryContent)): ?>
    <div class="grid">
        <div class="hor-scroll" style="max-height:300px;overflow-y:auto;">
            <table cellspacing="0" id="warehouse_history_id_table" class="data">
                <colgroup>
                    <col>
                    <col width="280">
                    <col width="280">
                </colgroup>
                <thead>
                    <tr class="headings">
                        <th>
                            <span class="nobr">
                                <span class="sort-title"><?php echo $this->__('Field Name') ?></span>
                            </span>
                        </th>
                        <th>
                            <span class="nobr">
                                <span class="sort-title">
                                    <?php echo $this->__('Old Value'); ?>
                                </span>         
                            </span>
                        </th>
                        <th>
                            <span class="nobr">
                                <span class="sort-title">
                                    <?php echo $this->__('New Value'); ?>
                                </span>         
                            </span>
                        </th>
                    </tr>   
                </thead>    
                <tbody>
                    <?php $i = 0 ?>
                    <?php foreach ($warehouseHistoryContent as $content): ?>
                        <?php $i++ ?>
                        <tr class="even pointer">
                            <td class=" ">
                                <?php echo $content->getData('field_name') ?>
                            </td>
                            <td class=" ">
                                <?php echo $content->getData('old_value') ?>                                
                            </td>
                            <td class=" last">
                                <?php echo $content->getData('new_value') ?>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
<?php else: ?>
    <?php echo $this->__('Not found any warehouse history!') ?>
<?php endif; ?>
