
<?php if ($this->getMethod()->getConfigData('instructions')): ?>
    <ul class="form-list checkout-agreements" id="payment_form_<?php echo $this->getMethodCode() ?>" style="display:none;">
        <li>
            <div class="<?php echo $this->getMethodCode() ?>-instructions-content agreement-content">
                <?php echo nl2br($this->getMethod()->getConfigData('instructions')) ?>
            </div>
        </li>
    </ul>
<?php endif; ?>
