<?php
/**
 * Customized addition of analytics.js prefered over ga.js with use of ec.js
 *
 * @author Joel Hart @mediotype
 * @var $this Mediotype_EnhancedEcommerce_Block_Page_BeforeBody
 */

//$host = 'test';
//$UA = 'test';

$host   = $this->getHost();
$UA     = $this->getGoogleAnalyticsUA();
?>

<script type="text/javascript">

    (function (i, s, o, g, r, a, m) {
        i['GoogleAnalyticsObject'] = r;
        i[r] = i[r] || function () {
            (i[r].q = i[r].q || []).push(arguments)
        }, i[r].l = 1 * new Date();
        a = s.createElement(o),
            m = s.getElementsByTagName(o)[0];
        a.async = 1;
        a.src = g;
        m.parentNode.insertBefore(a, m)
    })(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');

    ga('create', '<?php echo $UA ?>', '<?php echo $host ?>');
    ga('require', 'displayfeatures');
    ga('require', 'ec');

</script>
