
<?php
    $_productCollection=$this->getLoadedProductCollection();
	$_helper = $this->helper('catalog/output');
    $store = Mage::app()->getStore();
    $code  = $store->getCode();
    $aspect_ratio = Mage::getStoreConfig("porto_settings/category/aspect_ratio",$code);
    $ratio_width = Mage::getStoreConfig("porto_settings/category/ratio_width",$code);
    $ratio_height = Mage::getStoreConfig("porto_settings/category/ratio_height",$code);
    
//    echo $ratio_width . "--" . $ratio_height . "///" . $aspect_ratio; 
    
?>
<?php if(!$_productCollection->count()): ?>
<p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>
<div class="category-products">
    <?php echo $this->getToolbarHtml() ?>
    <?php // List mode ?>
    <?php if($this->getMode()!='grid'): ?>
    <?php $_iterator = 0; ?>
    
    <?php 
    /* COLORS AND ATTRIBUTES SWATCHES HELPER */
    $_swatches_helper = $this->helper("attributeswatches/product_list")->setDimensions(300,300); /*set the dimensions here...*/
    ?>
    
    <ol class="products-list product-items" id="products-list">
    <?php foreach ($_productCollection as $_product): ?>
        <?php
        /* MANGOEXTENSIONS */
        /* -SWATCHES HTML OUTPUT */
        $_swatches = $_swatches_helper->setProduct($_product)->processSwatches();
        /* EOF -SWATCHES HTML OUTPUT */
        ?>
        
        <li class="item"><div class="item-area">
                <div class="product-image-area">
                    <?php // Product Image  
                    /* MANGOEXTENSIONS */
                    /* CHANGE THE SOURCE OF THE PRODUCT IMAGE TO CHANGE ACCORDING TO THE LAYERED NAVIGATION */
                    ?>
                    <a href="<?php echo $_swatches["product_url"] ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
                    <?php
                        if(Mage::getStoreConfig("porto_settings/category/alternative_image", $code)){
                    ?>
                        <img class="defaultImage catalog-product-image" src="<?php echo $_swatches["product_image"] ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>"/>
                        <img class="hoverImage" src="<?php if($aspect_ratio):?><?php echo $this->helper('catalog/image')->init($_product, 'thumbnail')->constrainOnly(FALSE)->keepAspectRatio(TRUE)->keepFrame(FALSE)->resize(300);?><?php else: ?><?php echo $this->helper('catalog/image')->init($_product, 'thumbnail')->resize($ratio_width,$ratio_height); ?><?php endif; ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'thumbnail'), null, true) ?>"/>
                    <?php
                        } else {
                    ?>
                        <img src="<?php echo $_swatches["product_image"] ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>"  class="catalog-product-image"/>
                    <?php
                        }
                    ?>
                    </a>
                    <?php 
                        $productLabels = Array();
                        // Get the Special Price
                        $specialprice = Mage::getModel('catalog/product')->load($_product->getId())->getSpecialPrice(); 
                        // Get the Special Price FROM date
                        $specialPriceFromDate = Mage::getModel('catalog/product')->load($_product->getId())->getSpecialFromDate();
                        // Get the Special Price TO date
                        $specialPriceToDate = Mage::getModel('catalog/product')->load($_product->getId())->getSpecialToDate();
                        // Get Current date
                        $today =  time();
                     
                        /*if ($specialprice){
                            if($today >= strtotime( $specialPriceFromDate) && $today <= strtotime($specialPriceToDate) || $today >= strtotime( $specialPriceFromDate) && is_null($specialPriceToDate)){
                                if(Mage::getStoreConfig("porto_settings/product_label/sale", $code)){
                    ?>
                                <div class="product-label" style="right: 10px;"><span class="sale-product-icon"><?php echo $this->__('Sale');?>!</span></div>
                    <?php       
                                }
                            }
                        }*/
                        $now = date("Y-m-d");
                        $newsFrom= substr($_product->getData('news_from_date'),0,10);
                        $newsTo=  substr($_product->getData('news_to_date'),0,10);
                        if ($newsTo != '' || $newsFrom != ''){
                            if (($newsTo != '' && $newsFrom != '' && $now>=$newsFrom && $now<=$newsTo) || ($newsTo == '' && $now >=$newsFrom) || ($newsFrom == '' && $now<=$newsTo))
                            {
                                if(Mage::getStoreConfig("porto_settings/product_label/new", $code)){
                                  //$productLabels[] = $this->__('New');
                                }
                            }
                        }
                        if(count($productLabels) > 0){
                          echo '<div class="product-label">';
                          foreach ($productLabels as $product_label){
                            echo '<span class="product-label-icon '.strtolower($product_label).'-product-icon">'.$product_label.'</span>';
                          }
                          echo '</div>';
                        }
                    ?>
                </div>
                <div class="details-area">
                    <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h2>
                    <?php if($_product->getRatingSummary()): ?>
                    <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
                    <?php else: ?>
                        <div class="ratings">
                            <div class="rating-box">
                                <div class="rating" style="width:0"></div>
                            </div>
                        </div>
                    <?php endif; ?>
                    
                    <!-- SWATCHES HTML OUTPUT -->
                        <?php
                        /* INCLUDE AVAILABILITY IF ENABLED IN BACKEND OPTIONS */
                        echo $_swatches_helper->showAvailability();
                        /* SWATCHES CODE */
                        echo $_swatches["swatches"];
                        ?> 
                    
                    <div class="short-desc">
                        <?php echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                    </div>
                    <div class="action-area">
                        <?php echo $this->getPriceHtml($_product, true) ?>
                        <div class="actions">
                            <?php if($_product->isSaleable()): ?>
                                <?php  if ( !($_product->getTypeInstance(true)->hasOptions($_product)/*$_product->getData('has_options')*/ || $_product->isGrouped()) ) :  ?>
                                    <a href="<?php if(Mage::getStoreConfig("ajaxcart/addtocart/enablecategory", $code)):?>javascript:setLocationAjax('<?php echo $this->getAddToCartUrl($_product) ?>')<?php else: ?><?php echo $this->getAddToCartUrl($_product) ?><?php endif; ?>" class="addtocart" title="<?php echo $this->__('Add to Cart') ?>"><i class="icon-cart"></i><span>&nbsp;<?php echo $this->__('Add to Cart') ?></span></a>
                                <?php else : ?>
                                    <a href="<?php if(Mage::getStoreConfig("ajaxcart/addtocart/enablecategory", $code)):?>javascript:showOptions('<?php echo $_product->getId()?>')<?php else: ?><?php echo $this->getAddToCartUrl($_product) ?><?php endif; ?>" class="addtocart" title="<?php echo $this->__('Add to Cart') ?>"><i class="icon-cart"></i><span>&nbsp;<?php echo $this->__('Add to Cart') ?></span></a>
                                    <a href='<?php echo $this->getUrl('ajaxcart/index/options',array('product_id'=>$_product->getId()));?>' class='fancybox' id='fancybox<?php echo $_product->getId()?>' style='display:none'>Options</a>
                                <?php endif;?>
                            <?php else: ?>
                                <a href="javascript:void(0);" class="addtocart outofstock" title="<?php echo $this->__('Out of stock') ?>"><?php echo $this->__('Out of stock') ?></span></a>
                            <?php endif; ?>
                            <?php if ($this->helper('wishlist')->isAllow()) : ?>
                            <a href="<?php if(Mage::getStoreConfig("ajaxcart/addtolinks/enablecategory", $code)):?>javascript:ajaxWishlist('<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>','<?php echo $_product->getId()?>');<?php else: ?><?php echo $this->helper('wishlist')->getAddUrl($_product) ?><?php endif; ?>" class="addtowishlist" title="<?php echo $this->__('Add to Wishlist') ?>"><i class="icon-wishlist"></i></a>
                            <?php endif; ?>

                            <?php if(Mage::getStoreConfig("porto_settings/category/compare", $code) && $_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                                <a href="<?php if(Mage::getStoreConfig("ajaxcart/addtolinks/enablecategory", $code)):?>javascript:ajaxCompare('<?php echo $_compareUrl ?>','<?php echo $_product->getId()?>');<?php else: ?><?php echo $_compareUrl ?><?php endif; ?>" class="comparelink" title="<?php echo $this->__('Add to Compare') ?>"><i class="icon-compare"></i></a>
                            <?php endif; ?>
                            <?php
                            if( Mage::getStoreConfig("quickview/general/enableview", $code) ){
                                $base_url = $this->getUrl();
                                if(strpos($base_url,'?')!==false)
                                    $base_url = split("?",$this->getUrl());
                                if(is_array($base_url))
                                    $base_url = $base_url[0];
                                if(strpos($base_url,'index.php')!==false){
                                    $base_url = str_replace('index.php/','',$base_url);
                                    $base_url .= "index.php/quickview/index/view/";
                                }else{
                                    $base_url .= "quickview/index/view/";
                                }
                                $quickview_url = $base_url."id/".$_product->getId();
                            ?>
                                <a href="<?php echo $quickview_url; ?>" class="quickviewlink quickview-icon" title="<?php echo $this->__("Quick View"); ?>"><i class="icon-search"></i></a>
                            <?php
                            }
                            ?>
                            <div class="clearer"></div>
                        </div>
                    </div>
                </div>
                <div class="clearer"></div>
            </div></li>
    <?php endforeach; ?>
    </ol>
    <script type="text/javascript">decorateList('products-list', 'none-recursive')</script>

    <?php else: ?>

    <?php // Grid Mode ?>

    <?php 
    /* COLORS AND ATTRIBUTES SWATCHES HELPER */
    $_swatches_helper = $this->helper("attributeswatches/product_list")->setDimensions(300, 300); /* set the dimensions here... */
    ?>
    
    <?php $_collectionSize = $_productCollection->count() ?>
    <?php
    //$_columnCount = Mage::getStoreConfig("porto_settings/category_grid/columns",$code);
    $_columnCount = $this->getColumnCount() ? $this->getColumnCount() : Mage::getStoreConfig("porto_settings/category_grid/columns",$code);
    ?>
    <ul <?php /* FAB-95 Start/**/ ?>id="myProductList" <?php /* FAB-95 End/**/ ?>class="products-grid product-items columns<?php echo $_columnCount; ?><?php if(!Mage::getStoreConfig("porto_settings/category_grid/show_addtolinks", $code)):?> hide-addtolinks<?php endif; ?><?php if(!Mage::getStoreConfig("porto_settings/category_grid/show_addtocart", $code)):?> hide-addtocart<?php endif; ?><?php if(Mage::getStoreConfig("porto_settings/category_grid/move_actions", $code)):?> move-action<?php endif; ?>">
    <?php $i=0; /* FAB-95 Start/**/ $mycount=0; /* FAB-95 End/**/ foreach ($_productCollection as $_product): ?>
            <?php
            /* MANGOEXTENSIONS */
            /* -SWATCHES HTML OUTPUT */
            $_swatches = $_swatches_helper->setProduct($_product)->processSwatches();
            /* EOF -SWATCHES HTML OUTPUT */
            $stock = Mage::getModel('cataloginventory/stock_item')->loadByProduct($_product);
			/* FAB-95 Start/**/ $mycount++; /* FAB-95 End/**/
            ?>
        
            <li class="item <?php /* FAB-95 Start/**/ ?>myProductLi<?php /* FAB-95 End/**/ ?>" <?php /* FAB-95 Start/**/ ?>product-index="<?php echo $mycount; ?>"<?php /* FAB-95 End/**/ ?>>
              <div class="item-area">
                <div class="price-discount-percentage">
                <?php
                  $_finalPrice=$_product->getFinalPrice();
                  $_price=$_product->getPrice();
                  if($_finalPrice < $_price){
                    $_savePercent = 100 - round(($_finalPrice / $_price)*100);
                    echo '<span class="perc-text">'.$_savePercent.'</span>';
                  }
                ?>
                </div>
                <div class="product-image-area">
                    <?php
                    if( Mage::getStoreConfig("quickview/general/enableview", $code) ){
                        $base_url = $this->getUrl();
                        if(strpos($base_url,'?')!==false)
                            $base_url = split("?",$this->getUrl());
                        if(is_array($base_url))
                            $base_url = $base_url[0];
                        if(strpos($base_url,'index.php')!==false){
                            $base_url = str_replace('index.php/','',$base_url);
                            $base_url .= "index.php/quickview/index/view/";
                        }else{
                            $base_url .= "quickview/index/view/";
                        }
                        $quickview_url = $base_url."id/".$_product->getId();
                        ?>
                        <a href="<?php echo $quickview_url; ?>" class="quickview-icon"><i class="icon-export"></i><span><?php echo $this->__("Quick View"); ?></span></a>
                    <?php
                    }
                    ?>
                        <?php // Product Image  
                        /* MANGOEXTENSIONS */
                        /* CHANGE THE SOURCE OF THE PRODUCT IMAGE TO CHANGE ACCORDING TO THE LAYERED NAVIGATION */
                        ?>
                    <a href="<?php echo $_swatches["product_url"] ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
                    <?php
                        if(Mage::getStoreConfig("porto_settings/category/alternative_image", $code)){
                    ?>

                        <img class="defaultImage catalog-product-image" src="<?php echo $_swatches["product_image"]; ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>"/>
                        <img class="hoverImage" src="<?php if($aspect_ratio):?><?php echo $this->helper('catalog/image')->init($_product, 'thumbnail')->constrainOnly(FALSE)->keepAspectRatio(TRUE)->keepFrame(TRUE)->resize(300, 300);?><?php else: ?><?php echo $this->helper('catalog/image')->init($_product, 'thumbnail')->resize($ratio_width,$ratio_height); ?><?php endif; ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'thumbnail'), null, true) ?>"/>

                    <?php
                        } else {
                    ?>
                        <img src="<?php echo $_swatches['product_image'];?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>"  class="catalog-product-image"/>
                    <?php
                        }
                    ?>
                    </a>
                    <?php 
                        $productLabels = Array();
                        // Get the Special Price
                        $specialprice = Mage::getModel('catalog/product')->load($_product->getId())->getSpecialPrice(); 
                        // Get the Special Price FROM date
                        $specialPriceFromDate = Mage::getModel('catalog/product')->load($_product->getId())->getSpecialFromDate();
                        // Get the Special Price TO date
                        $specialPriceToDate = Mage::getModel('catalog/product')->load($_product->getId())->getSpecialToDate();
                        // Get Current date
                        $today =  time();
                     
                        /*if ($specialprice){
                            if($today >= strtotime( $specialPriceFromDate) && $today <= strtotime($specialPriceToDate) || $today >= strtotime( $specialPriceFromDate) && is_null($specialPriceToDate)){
                                if(Mage::getStoreConfig("porto_settings/product_label/sale", $code)){
                    ?>
                                <div class="product-label" style="right: 10px;"><span class="sale-product-icon"><?php echo $this->__('Sale');?></span></div>
                    <?php       
                                }
                            }
                        }*/
                        $now = date("Y-m-d");
                        $newsFrom= substr($_product->getData('news_from_date'),0,10);
                        $newsTo=  substr($_product->getData('news_to_date'),0,10);
                        if ($newsTo != '' || $newsFrom != ''){
                            if (($newsTo != '' && $newsFrom != '' && $now>=$newsFrom && $now<=$newsTo) || ($newsTo == '' && $now >=$newsFrom) || ($newsFrom == '' && $now<=$newsTo))
                            {
                                if(Mage::getStoreConfig("porto_settings/product_label/new", $code)){
                                  //$productLabels[] = $this->__('New');
                                }
                            }
                        }
                        if(count($productLabels) > 0){
                          echo '<div class="product-label">';
                          foreach ($productLabels as $product_label){
                            echo '<span class="product-label-icon '.strtolower($product_label).'-product-icon">'.$product_label.'</span>';
                          }
                          echo '</div>';
                        }
                    ?>
                </div>
                <div class="details-area">
                    <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h2>
                    <?php
                    if($_product->getTypeId() == 'configurable') {
                      $_swatches_ids = array();

                      $conf = Mage::getModel('catalog/product_type_configurable')->setProduct($_product);
                      $simpleProds = Mage::getModel('catalog/product')->getCollection()
                        ->addAttributeToSelect('fabric_color')
                        ->addAttributeToSelect('leather_color')
                        ->addAttributeToFilter('entity_id', $conf->getUsedProductCollection()->getAllIds())
                        ->addAttributeToFilter('status', array('eq' => Mage_Catalog_Model_Product_Status::STATUS_ENABLED));

                      foreach($simpleProds as $simple_product){
                        if($fabricColor = $simple_product->getData('fabric_color')) {
                          $_swatches_ids[] = $fabricColor;
                        }
                        if($leatherColor = $simple_product->getData('leather_color')) {
                          $_swatches_ids[] = $leatherColor;
                        }
                      }

                      $_options = Mage::getModel('attributeswatches/attributeswatches')->getCollection()
                        ->setOrder('value', Varien_Data_Collection::SORT_ORDER_ASC)
                        ->addFieldToFilter('main_table.option_id', array('in' => $_swatches_ids));
                    // FAB-83 code start
                      $attributeId = Mage::getResourceModel('eav/entity_attribute')->getIdByCode('catalog_product', 'fabric_color');
                    // FAB-83 code end
                      echo '<ul class="fabric-color-swatches clearfix">';
                      $cnt = 1;
                      foreach($_options as $k=>$ps) {
                        // FAB-83 code start
                          echo '<li><a href="'.$_product->getProductUrl().'#'.$attributeId.'='.$ps['option_id'].'"><img class="tooltip" src="/media/attributeswatches/'.$ps['filename'].'" alt="'.$ps['value'].'" title="'.$ps['value'].'"></a></li>';
                        // FAB-83 code end
                          if(++$cnt > 5) break;
                      }
					  echo '<li class="more-swatches" options="'.count($_options).'"><a href="'.$_product->getProductUrl().'">More</a></li>';
                      
					  
                      echo '</ul>';
                    }else{
						echo '<ul class="fabric-color-swatches clearfix"><li></li></ul>';
					}
                    ?>
                    <?php if($_product->getRatingSummary()): ?>
                    <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
                    <?php else: ?>
                        <div class="ratings">
                            <div class="rating-box">
                                <div class="rating" style="width:0"></div>
                            </div>
                        </div>
                    <?php endif; ?>
                    <?php echo $this->getPriceHtml($_product, true) ?>

                    
                    <!-- SWATCHES HTML OUTPUT -->
                        <?php
                        /* INCLUDE AVAILABILITY IF ENABLED IN BACKEND OPTIONS */
                        echo $_swatches_helper->showAvailability();
                        /* SWATCHES CODE */
                        echo $_swatches["swatches"];
                        ?>
                    
                    
                    
                    <div class="actions">
                        <?php if ($this->helper('wishlist')->isAllow()) : ?>
                        <a href="<?php if(Mage::getStoreConfig("ajaxcart/addtolinks/enablecategory", $code)):?>javascript:ajaxWishlist('<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>','<?php echo $_product->getId()?>');<?php else: ?><?php echo $this->helper('wishlist')->getAddUrl($_product) ?><?php endif; ?>" class="addtowishlist" title="<?php echo $this->__('Add to Wishlist') ?>"><i class="icon-wishlist"></i></a>
                        <?php endif; ?>
                        <?php if($_product->isSaleable()): ?>
                            <?php  if ( !($_product->getTypeInstance(true)->hasOptions($_product)/*$_product->getData('has_options')*/ || $_product->isGrouped()) ) :  ?>
                                <a href="<?php if(Mage::getStoreConfig("ajaxcart/addtocart/enablecategory", $code)):?>javascript:setLocationAjax('<?php echo $this->getAddToCartUrl($_product) ?>')<?php else: ?><?php echo $this->getAddToCartUrl($_product) ?><?php endif; ?>" class="addtocart" title="<?php echo $this->__('Add to Cart') ?>"><i class="icon-cart"></i><span>&nbsp;<?php echo $this->__('Add to Cart') ?></span></a>
                            <?php else : ?>
                                <a href="<?php if(Mage::getStoreConfig("ajaxcart/addtocart/enablecategory", $code)):?>javascript:showOptions('<?php echo $_product->getId()?>')<?php else: ?><?php echo $this->getAddToCartUrl($_product) ?><?php endif; ?>" class="addtocart" title="<?php echo $this->__('Add to Cart') ?>"><i class="icon-cart"></i><span>&nbsp;<?php echo $this->__('Add to Cart') ?></span></a>
                                <a href='<?php echo $this->getUrl('ajaxcart/index/options',array('product_id'=>$_product->getId()));?>' class='fancybox' id='fancybox<?php echo $_product->getId()?>' style='display:none'>Options</a>
                            <?php endif;?>
                        <?php else: ?>
                            <a href="javascript:void(0);" class="addtocart outofstock" title="<?php echo $this->__('Out of stock') ?>"><?php echo $this->__('Out of stock') ?></span></a>
                        <?php endif; ?>
                        <?php if(Mage::getStoreConfig("porto_settings/category/compare", $code) && $_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                            <a href="<?php if(Mage::getStoreConfig("ajaxcart/addtolinks/enablecategory", $code)):?>javascript:ajaxCompare('<?php echo $_compareUrl ?>','<?php echo $_product->getId()?>');<?php else: ?><?php echo $_compareUrl ?><?php endif; ?>" class="comparelink" title="<?php echo $this->__('Add to Compare') ?>"><i class="icon-compare"></i></a>
                        <?php endif; ?>
                        <div class="clearer"></div>
                    </div>
                      <div class="claimed-progress-wrap">
                          <?php
                          $stockQty = (int)$stock->getQty();
                          if($stockQty < 0) $stockQty = 0;
                          $totalQty = (int)$_product->ordered_qty + $stockQty;
                          $perc = 0;
                          if($totalQty){
                            $perc = ($stockQty/$totalQty) * 100;
                          }
                          ?>
                          <div class="claimed-progress" data-totalqty="<?php echo $totalQty; ?>" data-claimed="<?php echo (int)$_product->ordered_qty; ?>">
                              <span class="left-bubble"><?php echo $stockQty; ?></span>
                              <span style="width: <?php echo $perc ?>%"></span>
                              <span class="right-bubble <?php if($perc <= 0){ echo "text-danger"; } ?>">
                                <?php
                                  if($perc <= 0){
                                    echo "barang telah habis!";
                                  }else{
                                    echo "barang tersedia!";
                                  }
                                ?>
                            </span>
                          </div>
                      </div>
                    
                </div>
            </div></li>
        <?php endforeach ?>
        </ul>
		<?php /***** FAB - 95 Start *******/  ?>
		<input type="hidden" id="scrollPageNum" value="<?php $valueOfP=Mage::app()->getRequest()->getParam('p'); if($valueOfP>1){ echo $valueOfP; }else{ echo '1'; }?>">
		<input type="hidden" id="scrollEndPageNum" value="<?php echo $_productCollection->getLastPageNumber(); ?>">
		<input type="hidden" id="isRequested" value="0">
		<input type="hidden" id="currentPageSize" value="<?php echo $_productCollection->getPageSize(); ?>">
		<input type="hidden" id="TotalProductsInList" value="<?php echo $_productCollection->getPageSize(); ?>">
		<?php /***** FAB - 95 end *******/  ?>
		<script type="text/javascript">
            jQuery('.col-main .products-grid li:nth-child(2n)').addClass('nth-child-2n');
            jQuery('.col-main .products-grid li:nth-child(2n+1)').addClass('nth-child-2np1');
            jQuery('.col-main .products-grid li:nth-child(3n)').addClass('nth-child-3n');
            jQuery('.col-main .products-grid li:nth-child(3n+1)').addClass('nth-child-3np1');
            jQuery('.col-main .products-grid li:nth-child(4n)').addClass('nth-child-4n');
            jQuery('.col-main .products-grid li:nth-child(4n+1)').addClass('nth-child-4np1');
            jQuery('.col-main .products-grid li:nth-child(5n)').addClass('nth-child-5n');
            jQuery('.col-main .products-grid li:nth-child(5n+1)').addClass('nth-child-5np1');
            jQuery('.col-main .products-grid li:nth-child(6n)').addClass('nth-child-6n');
            jQuery('.col-main .products-grid li:nth-child(6n+1)').addClass('nth-child-6np1');
            jQuery('.col-main .products-grid li:nth-child(7n)').addClass('nth-child-7n');
            jQuery('.col-main .products-grid li:nth-child(7n+1)').addClass('nth-child-7np1');
            jQuery('.col-main .products-grid li:nth-child(8n)').addClass('nth-child-8n');
            jQuery('.col-main .products-grid li:nth-child(8n+1)').addClass('nth-child-8np1');
			
			jQuery(document).ready(function(){
				manageSwatches();
			});
			jQuery(window).resize(function() {
				manageSwatches();
			});
			
			function manageSwatches(){
				var winWidth=jQuery(window).width();
				if(winWidth>767){
					jQuery(".show-mobile-more-swatches").addClass("hide");
					jQuery(".nth-child-4n").removeClass("hide");
					jQuery(".nth-child-5n").removeClass("hide");
					jQuery(".nth-child-6n").removeClass("hide");
					jQuery(".nth-child-7n").removeClass("hide");
					jQuery( ".fabric-color-swatches li:nth-child(4)" ).removeClass('hide');
					jQuery( ".fabric-color-swatches li:nth-child(5)" ).removeClass('hide');
					jQuery( ".fabric-color-swatches li:nth-child(6)" ).removeClass('hide');
					jQuery( ".fabric-color-swatches li:nth-child(7)" ).removeClass('hide');
					jQuery(".more-swatches").each(function() {
						if(jQuery( this ).attr("options")>5){
							jQuery( this ).removeClass("hide");
						}else{
							jQuery( this ).addClass("hide");
						}
					});
					
				}else{
					jQuery(".nth-child-4n").addClass("hide");
					jQuery(".nth-child-5n").addClass("hide");
					jQuery(".nth-child-6n").addClass("hide");
					jQuery(".nth-child-7n").addClass("hide");
					jQuery( ".fabric-color-swatches li:nth-child(4)" ).addClass('hide');
					jQuery( ".fabric-color-swatches li:nth-child(5)" ).addClass('hide');
					jQuery( ".fabric-color-swatches li:nth-child(6)" ).addClass('hide');
					jQuery( ".fabric-color-swatches li:nth-child(7)" ).addClass('hide');
					jQuery(".more-swatches").each(function() {
						if(jQuery( this ).attr("options")>3){
							jQuery( this ).removeClass("hide");
						}else{
							jQuery( this ).addClass("hide");
						}
					});
					
				}
			}
/***** FAB - 95 Start *******/		

			jQuery(window).scroll(function(){
				//alert("hello");
				var hT = jQuery('#myProductList').offset().top;
				var hH = jQuery('#myProductList').outerHeight();
				var wH = jQuery(window).height();
				var wS = jQuery(this).scrollTop();
				var wHNew=wH*3;
				var winWidth=jQuery(window).width();
				if (wS > (hT+hH-wHNew)){
					
					if(winWidth>767){
					
					}else{
						infiniteScrollForMobile();
					}
				}
				
				if(winWidth<767){
					var currentLi=2;
					var currentCount=0;
					var index=0;
					jQuery('.myProductLi').each(function(i, obj) {
						var LiTop=jQuery(this).offset().top;
						var liheight=jQuery(this).height();
						//console.log("index : "+index+", top : "+LiTop+", height : "+liheight);
						if(liheight>0){
							if(wS>LiTop+liheight-wH){
								
								currentLi=index+1;
							}
							index++;
						}
						
					});
					var total=index;
					jQuery("#TotalProductsInList").val(total);
					if(jQuery('#currentProductIsBlock').length==0){
						jQuery('#myProductList').after('<div id="currentProductIsBlock" style="position: fixed;z-index: 100000000;bottom: 10px;height: 50px;opacity: 0.8;margin-left: -75px;width: 150px;left: 50%;text-align: center;background-color: black;border-radius: 5px;color: white;padding-top: 15px;"></div>');
					}
					jQuery('#currentProductIsBlock').html(currentLi+" of <?php echo $_productCollection->getSize(); ?>");
					clearTimeout(jQuery.data(this, 'scrollTimer'));
					jQuery.data(this, 'scrollTimer', setTimeout(function() {
						jQuery('#currentProductIsBlock').remove();
					}, 2000));
					
				}
				
			});
			jQuery(document).ready(function(){
				hideAndShowPaging();
			});
			jQuery(window).resize(function() {
				hideAndShowPaging();
			});
			
			function hideAndShowPaging(){
				var winWidth=jQuery(window).width();
				if(winWidth>767){
					jQuery(".pager").removeClass('hide');
					jQuery(".limiter").removeClass('hide');
					if(jQuery('#myProductLoaderImg').length>0){
						jQuery('#myProductLoaderImg').remove();
					}
					if(jQuery('#currentProductIsBlock').length>0){
						jQuery('#currentProductIsBlock').remove();
					}
					
				}else{
					jQuery(".pager").addClass('hide');
					jQuery(".limiter").addClass('hide');
					
				}
			}
			function infiniteScrollForMobile(){
					var currentPageNum=jQuery('#scrollPageNum').val();
					var scrollEndPageNum=jQuery('#scrollEndPageNum').val();
					if(currentPageNum<scrollEndPageNum){
						var nextPageNum=parseInt(currentPageNum)+1;
						var categoryUrlPage=jQuery('#ptech_multilayer_ajax').val();
						var isRequested=jQuery('#isRequested').val();
						var url=categoryUrlPage;
						if(categoryUrlPage.indexOf('?') >= 0){
							url=url+'&p='+nextPageNum;
						}else{
							url=url+'?p='+nextPageNum;
						}
						if(isRequested==0){
							jQuery('#isRequested').val("1");
							jQuery.ajax({
								type: "POST",
								url: url,
								data: "",
								beforeSend: function() {
									jQuery('#myProductList').append('<img id="myProductLoaderImg" src="/media/infinitescroll/loading_spinner.gif" style="margin: auto;height: 50px;">');
								},
								success: function(data) {
									if(jQuery('#myProductLoaderImg').length>0){
										jQuery('#myProductLoaderImg').remove();
									}
									var jsonObj=JSON.parse(data);
									//console.log(jsonObj);
									var elements = jQuery(jsonObj.products);
									var found = jQuery('#myProductList', elements).html();
									jQuery('#myProductList').append(found);
									jQuery('#isRequested').val("0");
									jQuery('#scrollPageNum').val(nextPageNum);
									jQuery( ".fabric-color-swatches li:nth-child(4)" ).addClass('hide');
									jQuery( ".fabric-color-swatches li:nth-child(5)" ).addClass('hide');
									jQuery( ".fabric-color-swatches li:nth-child(6)" ).addClass('hide');
									jQuery( ".fabric-color-swatches li:nth-child(7)" ).addClass('hide');
									jQuery(".more-swatches").each(function() {
									if(jQuery( this ).attr("options")>3){
										jQuery( this ).removeClass('hide');
									}else{
										jQuery( this ).addClass('hide');
									}
									});
								}
							});
						}
					}
			}
			
/***** FAB - 95 End *******/
        </script>
    <?php endif; ?>

    <div class="toolbar-bottom">
        <?php echo $this->getToolbarHtml() ?>
    </div>
</div>
<?php endif; ?>
