
<!--<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">-->
<!--<link rel="stylesheet" href="/skin/frontend/smartwave/porto/css/supplierfrontendproductuploader/bootstrap.min.css">-->
<!--<script src="/skin/frontend/smartwave/porto/js/supplierfrontendproductuploader/bootstrap.min.js"></script>-->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
<style>
    .close {
  float: right;
  font-size: 21px;
  font-weight: bold;
  line-height: 1;
  color: #000;
  text-shadow: 0 1px 0 #fff;
  filter: alpha(opacity=20);
  opacity: .2;
}
.close:hover,
.close:focus {
  color: #000;
  text-decoration: none;
  cursor: pointer;
  filter: alpha(opacity=50);
  opacity: .5;
}
button.close {
  -webkit-appearance: none;
  padding: 0;
  cursor: pointer;
  background: transparent;
  border: 0;
}
.modal-open {
  overflow: hidden;
}
.modal {
  position: fixed;
  top: 0;
  right: 0;
  bottom: 0;
  left: 0;
  z-index: 1050;
  display: none;
  overflow: hidden;
  -webkit-overflow-scrolling: touch;
  outline: 0;
}
.modal.fade .modal-dialog {
  -webkit-transition: -webkit-transform .3s ease-out;
       -o-transition:      -o-transform .3s ease-out;
          transition:         transform .3s ease-out;
  -webkit-transform: translate(0, -25%);
      -ms-transform: translate(0, -25%);
       -o-transform: translate(0, -25%);
          transform: translate(0, -25%);
}
.modal.in .modal-dialog {
  -webkit-transform: translate(0, 0);
      -ms-transform: translate(0, 0);
       -o-transform: translate(0, 0);
          transform: translate(0, 0);
}
.modal-open .modal {
  overflow-x: hidden;
  overflow-y: auto;
}
.modal-dialog {
  position: relative;
  width: auto;
  margin: 10px;
}
.modal-content {
  position: relative;
  background-color: #fff;
  -webkit-background-clip: padding-box;
          background-clip: padding-box;
  border: 1px solid #999;
  border: 1px solid rgba(0, 0, 0, .2);
  border-radius: 6px;
  outline: 0;
  -webkit-box-shadow: 0 3px 9px rgba(0, 0, 0, .5);
          box-shadow: 0 3px 9px rgba(0, 0, 0, .5);
}
.modal-backdrop {
  position: fixed;
  top: 0;
  right: 0;
  bottom: 0;
  left: 0;
  z-index: 1040;
  background-color: #000;
}
.modal-backdrop.fade {
  filter: alpha(opacity=0);
  opacity: 0;
}
.modal-backdrop.in {
  filter: alpha(opacity=50);
  opacity: .5;
}
.modal-header {
  padding: 15px;
  border-bottom: 1px solid #e5e5e5;
}
.modal-header .close {
  margin-top: -2px;
}
.modal-title {
  margin: 0;
  line-height: 1.42857143;
}
.modal-body {
  position: relative;
  padding: 15px;
}
.modal-footer {
  padding: 15px;
  text-align: right;
  border-top: 1px solid #e5e5e5;
}
.modal-footer .btn + .btn {
  margin-bottom: 0;
  margin-left: 5px;
}
.modal-footer .btn-group .btn + .btn {
  margin-left: -1px;
}
.modal-footer .btn-block + .btn-block {
  margin-left: 0;
}
.modal-scrollbar-measure {
  position: absolute;
  top: -9999px;
  width: 50px;
  height: 50px;
  overflow: scroll;
}
@media (min-width: 768px) {
  .modal-dialog {
    width: 600px;
    margin: 30px auto;
  }
  .modal-content {
    -webkit-box-shadow: 0 5px 15px rgba(0, 0, 0, .5);
            box-shadow: 0 5px 15px rgba(0, 0, 0, .5);
  }
  .modal-sm {
    width: 300px;
  }
}
@media (min-width: 992px) {
  .modal-lg {
    width: 900px;
  }
}
    
    
@media (max-width:767px){
    .breadcrumbs_mobile_view{display: none;}
}
/*FAB-130 css starts here*/
.selected-attr{    display: inline-block;
    background: #f8edd9;
    width: 100%;
    padding: 10px;
    margin-bottom: 20px; text-align: center;}
.selected-attr ul{display: inline-block;
    width:auto;}
.selected-attr li{display: inline-block;
    margin-right: 15px;}
.selected-attr label{    font-family: roboto-bold;
    margin-right: 15px;}
.selected-attr li span{cursor: pointer; font-weight: 700; font-size: 16px;}
/*FAB-130 css starts here*/
</style>
<?php
$_helper = $this->helper('catalog/output');
$helper_richsnippets = $this->helper('porto/richsnippets');
$store = Mage::app()->getStore();
$code  = $store->getCode();
$designers = array(
  "Sadhiya Hanindita" => array(
    "img" => "Profile-Sadhiya-Haninditas.png",
    "about" => "Sadhiya adalah salah satu pendiri dari FASA, pemenang penghargaan desain rumah yang memfokuskan dirinya kepada desain yang sustainable (berkelanjutan). Salah satu hasil dari FASA ditunjuk sebagai wakil Indonesia untuk dipamerkan di Messe Frankfurt."
  ),
  "Fitria Noviianti" => array(
    "img" => "Profile-Fitria-Noviiantis.png",
    "about" => "Fitria adalah salah satu pendiri biro konsultan desain dan arsitektur yang bernama SV-Living, ikut terlibat di dalam beberapa proyek seperti cafe, kantor, hingga furniture. Membuatnya memiliki pengalaman yang cukup tinggi di bidang desain."
  ),
  "Fabelio Design Studio" => array(
    "img" => "Fabelio-Design-Team1.png",
    "about" => "Perkenalkan kreator di balik desain eksklusif furnitur Fabelio: Marshall Utoyo, Priscilla Brain, dan Raymond Simandjuntak, profesional-profesional yang sudah berkecimpung dalam dunia furnitur sejak lama. Ide segar mereka tertuang dalam kreasi eksklusif Fabelio yang mampu menghangatkan rumah Anda."
  ),
  "Guida Arezzi" => array(
    "img" => "Profile-Guida-Arezzis.png",
    "about" => "Guida adalah seorang desainer yang sudah memiliki banyak brand ternama. Dari fashion sampai ke produk, bakat desainnya dapat dirasakan melalui setiap detail yang di hasilkannya."
  ),
  "Reza Anwar" => array(
    "img" => "Profile-Reza-Anwars.png",
    "about" => "Reza adalah salah satu desainer muda yang paling dicari di Indonesia. Reza terlibat dengan banyak proyek menarik di Jakarta dan Bandung (tempat co-working, rumah, iklan). Reza tidak hanya seorang desainer tapi juga konsultan desainer."
  )
);
?>
<?php
    $_product = $this->getProduct();
    $manufacturerName = $_product->getAttributeText('manufacturer');
    $designer = @$designers[$manufacturerName];
    $manufacturer = false;

    if(!$designer){
      $_manufacturer = Mage::getModel('zeon_manufacturer/manufacturer')
        ->setStoreId(Mage::app()->getStore()->getId())
        ->load($_product->getManufacturer(), 'manufacturer');
      $manufacturer = $_manufacturer->getData();
      if(!array_key_exists('manufacturer', $manufacturer)) $manufacturer = false;
    }
?>
<?php
    $product_type = $_product->getTypeId();
    $enabled_richsnippets = ($helper_richsnippets->isEnabled() && $product_type !== "grouped");
    $price_properties = "";
    
    if($enabled_richsnippets){
        $price_properties = $helper_richsnippets->getPriceProperties($_product);
    }
    
    $enable_addtocart_sticky = Mage::getStoreConfig("porto_settings/product_view/enable_addtocart_sticky",$code);
    $move_product_tab = Mage::getStoreConfig("porto_settings/product_view/move_product_tab",$code);
?>
<script type="text/javascript">
    <?php // TODO: fix bellow precision hack ?>
    var optionsPriceData = <?php echo $this->getJsonConfig() ?>;
    if(optionsPriceData.priceFormat){
      optionsPriceData.priceFormat.precision = 0;
      optionsPriceData.priceFormat.requiredPrecision = 0;
    }
    var optionsPrice = new Product.OptionsPrice(optionsPriceData);
</script>
<?php 
    $cbpa = @$_GET['cbpa'];
    if(isset($cbpa)){
        @session_start();
        setcookie('priceareacashback_id', strip_tags($cbpa), time() + (86400 * 7), "/");
    }
    /** FAB-130 Start /**/
?>
<div class="selected-attr hide">
        <label>Filter Aktif :</label>
        <ul id='deliverytimefiltersselected'>
           
        </ul>
    </div>
<?php /** FAB-130 End /**/ ?>
<!-- test -->
<div id="messages_product_view"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>

<div class="product-view <?php if($move_product_tab): ?>moved-tab<?php endif;?>" <?php if($enabled_richsnippets): ?><?php echo $helper_richsnippets->getProductItemscope(); ?><?php endif; ?>>
<div class="product-essential product-type-<?php echo $product_type; ?>">
<?php
if($enable_addtocart_sticky){
?>
        <div class="sticky-product hide <?php echo $sticky_header; ?>">
            <div class="container">
<?php
    $aspect_ratio = Mage::getStoreConfig("porto_settings/product_view/aspect_ratio", $code);
    $ratio_width = 600;
    $ratio_height = 600;
    if(Mage::getStoreConfig("porto_settings/product_view/ratio_width", $code))
        $ratio_width = Mage::getStoreConfig("porto_settings/product_view/ratio_width", $code);
    if(!$aspect_ratio){
        if(Mage::getStoreConfig("porto_settings/product_view/ratio_height", $code))
            $ratio_height = Mage::getStoreConfig("porto_settings/product_view/ratio_height", $code);
    }
    $ratio = $ratio_height / $ratio_width;
    $ratio_width = 50;
    $ratio_height = $ratio_width * $ratio_width;
    $sticky_header = "";
    if(!Mage::getStoreConfig("porto_settings/header/sticky_header", $code))
        $sticky_header = "no-sticky-header";
?>
                <div class="sticky-image">
                    <img src="<?php if($aspect_ratio):?><?php echo $this->helper('catalog/image')->init($_product, 'small_image')->constrainOnly(FALSE)->keepAspectRatio(TRUE)->keepFrame(FALSE)->resize(50);?><?php else: ?><?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($ratio_width,$ratio_height); ?><?php endif; ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>"/>
                </div>
                <div class="sticky-detail">
                    <div class="product-name-area">
                        <h2 class="product-name"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></h2>
                        <?php echo $this->getPriceHtml($_product) ?>
                    </div>
                    <?php 
                    if (Mage::helper('catalog')->isModuleEnabled('Mage_Review')):
                    if($_product->getRatingSummary()): 
                    ?>
                    <?php 
                        $review_html = $this->getReviewsSummaryHtml($_product, 'short');
                        if($review_html){
                            echo $review_html;
                        }else{
                    ?>
                        <div class="ratings">
                            <div class="rating-box">
                                <div class="rating" style="width:0"></div>
                            </div>
                        </div>
                    <?php                            
                        }
                    ?>
                    <?php else: ?>
                        <div class="ratings">
                            <div class="rating-box">
                                <div class="rating" style="width:0"></div>
                            </div>
                        </div>
                    <?php 
                    endif; 
                    endif;
                    ?>
                    <?php if ($this->displayProductStockStatus()): ?>
                        <?php if ($_product->isAvailable()): ?>
                            <p class="availability in-stock"><span>(<?php echo $this->__('In stock') ?>)</span></p>
                        <?php else: ?>
                            <p class="availability out-of-stock"><span>(<?php echo $this->__('Out of stock') ?>)</span></p>
                        <?php endif; ?>
                    <?php endif; ?>
                </div>
                <?php if($_product->isSaleable()): ?>
                <?php $buttonTitle = $this->__('Add to Cart'); ?>
                    <div class="add-to-cart">
                        <button type="button" title="<?php echo $buttonTitle ?>" class="button btn-cart" onclick="productAddToCartForm.submit(this)"><span><span><i class="icon-cart"></i><?php echo $buttonTitle ?></span></span></button>
                    </div>
                <?php endif; ?>
            </div>
        </div>
<?php
}
?>
        <div class="row">
            <div class="col-sm-8 border-right-desktop" ><!-- test -->
		<!--	<div class="product-name">
                      <h1 <?php if($enabled_richsnippets): ?>itemprop="name"<?php endif; ?>><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></h1>
                      <?php if(!is_null($_product->getAttributeText('manufacturer'))&&$_product->getAttributeText('manufacturer')!=""){?>
                      <p class="manufacturer">Oleh <?php echo $_product->getAttributeText('manufacturer'); ?></p>
                      <?php } ?>
                  </div>-->
                
                
                
                
                
              <div class="product-img-box slider-70" id="fab-prod-img-box" >
                <?php echo $this->getChildHtml('media_static') ?>
              </div>
                
                
                
                
                
                
                
                
                
            </div>
            <div class="product-shop col-sm-4 ">
            <?php
                if (Mage::getStoreConfig("porto_settings/product_view/prev_next",$code)){
            ?>
<!--                <div class="prev-next-products">
                    <?php $_prev = Mage::helper('porto')->getPreviousProduct(); ?>
                    <?php $_next = Mage::helper('porto')->getNextProduct(); ?>
                     
                    <?php if($_prev): ?>
                    <div class="product-nav product-prev">
                        <a href="<?php echo $_prev->getUrlPath();?>" title="<?php echo $this->__("Previous Product"); ?>">
                            <?php echo Mage::getStoreConfig("porto_settings/product_view/prev_text",$code); ?>
                        </a>
                        <div class="product-pop theme-border-color">
                            <?php
                            $image_src = $this->helper('catalog/image')->init($_prev, 'image')->constrainOnly(FALSE)->keepAspectRatio(TRUE)->keepFrame(FALSE)->resize(80);
                            ?>
                            <img class="product-image" src="<?php echo $image_src; ?>" alt="<?php echo $this->__('Previous');?>"/>
                            <h3 class="product-name"><?php echo $_helper->productAttribute($_prev, $_prev->getName(), 'name') ?></h3>
                        </div>
                    </div>
                    <?php endif; ?>
                    <?php if($_next): ?>
                    <div class="product-nav product-next">
                        <a class="product-next" href="<?php echo $_next->getUrlPath();?>" title="<?php echo $this->__("Next Product"); ?>"><?php echo Mage::getStoreConfig("porto_settings/product_view/next_text",$code); ?></a>
                        <div class="product-pop theme-border-color">
                            <?php
                            $image_src = $this->helper('catalog/image')->init($_next, 'image')->constrainOnly(FALSE)->keepAspectRatio(TRUE)->keepFrame(FALSE)->resize(80);
                            ?>
                            <img class="product-image" src="<?php echo $image_src; ?>" alt="<?php echo $this->__('Previous');?>"/>
                            <h3 class="product-name"><?php echo $_helper->productAttribute($_next, $_next->getName(), 'name') ?></h3>
                        </div>
                    </div>
                    <?php endif; ?>
                </div>-->
            <?php
                }
            ?>

              <form action="<?php echo $this->getSubmitUrl($_product) ?>" method="post" id="product_addtocart_form"<?php if($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>
                <?php echo $this->getBlockHtml('formkey') ?>
                <input type="hidden" name="product" value="<?php echo $_product->getId() ?>" />
                <input type="hidden" name="related_product" id="related-products-field" value="" />

                <div class="product-info" style="float:left;">
                <div class="product-name" style="position: absolute;right: 102%;z-index:2; width: 195%;">
                      <h1 <?php if($enabled_richsnippets): ?>itemprop="name"<?php endif; ?>><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></h1>
                      <?php if(!is_null($_product->getAttributeText('manufacturer'))&&$_product->getAttributeText('manufacturer')!=""){?>
                      <p class="manufacturer">Oleh <?php echo $_product->getAttributeText('manufacturer'); ?></p>
                      <?php } ?>
                  </div>  
                  <div <?php if($enabled_richsnippets) echo $helper_richsnippets->getOfferItemscope(); ?>>
                      <?php echo $this->getChildHtml('product_type_data'); ?>
                      <?php echo $this->getTierPriceHtml(); ?>
                      <?php echo $price_properties; ?>
                  </div>
<!--                  <div class="product-delivery-time">
                  <?php
                     echo $this->escapeHtml($_product->getDeliverytime()); // Shows module Webshops4All_ShowDeliverytime
                  ?>
                  </div>-->
                  <?php echo $this->getChildHtml('extrahint') ?>
                <?php if($_product->getData('assembly_required')): ?>
                  <div class="assembly-required">
                    <?php echo $this->__('This item requires installation by Fabelio team (only for Jabodetabek)'); ?>
                  </div>
                <?php endif;?>
                <!--  <?php if ($this->canEmailToFriend()): ?>
                    <p class="email-friend">
                      <a href="<?php echo $this->helper('catalog/product')->getEmailToFriendUrl($_product) ?>"><?php echo $this->__('Email to a Friend') ?></a>
                    </p>
                  <?php endif; ?> -->
                  <?php if($sku = $_product->getSku()): ?>
                      <?php if($enabled_richsnippets): ?><meta itemprop="productID" content="sku:<?php echo $sku; ?>" /><?php endif; ?>
                  <?php endif; ?>
                  <?php echo $this->getChildHtml('alert_urls') ?>
                  <?php echo $this->getChildHtml('other');?>
                </div>
                <?php if ($_product->getShortDescription()):?>
                  <div class="short-description">
                    <!-- <h2><?php echo $this->__('Quick Overview') ?></h2> -->
                    <p class="std" <?php if($enabled_richsnippets): ?>itemprop="description"<?php endif; ?>><?php echo $_helper->productAttribute($_product, ($_product->getShortDescription()), 'short_description') ?></p>
                  </div>
                <?php endif;?>
                <?php if (!$this->hasOptions()):?>
                  <div class="clearer"></div>
                  <div class="add-to-box">
                    <?php if($_product->isSaleable()): ?>
                      <?php echo $this->getChildHtml('addtocart') ?>
                      <?php if( $this->helper('wishlist')->isAllow() || $_compareUrl=$this->helper('catalog/product_compare')->getAddUrl($_product)): ?>
                      <?php endif; ?>
                    <?php endif; ?>
                    <?php echo $this->getChildHtml('addto') ?>
                  </div>
                  <?php echo $this->getChildHtml('extra_buttons') ?>
                <?php elseif (!$_product->isSaleable()): ?>
                    <div class="clearer"></div>
                    <div class="add-to-box">
                        <?php echo $this->getChildHtml('addto') ?>
                    </div>
                <?php endif; ?>

                <?php if ($_product->isSaleable() && $this->hasOptions()):?>
                    <?php echo $this->getChildChildHtml('container1', '', true, true) ?>
                <?php endif;?>
                <?php if ($_product->isSaleable() && $this->hasOptions()):?>
                    <?php echo $this->getChildChildHtml('container2', '', true, true) ?>
                <?php endif;?>
                <?php echo $this->getChildHtml('smartwave_sharetool'); ?>
                    
                <div class="product-page-usp ">
                  <div class="contact-fl clearfix">
                    <div class="pull-left">
                      <div class="icon">
                        <img src="/media/icons/usp-chat.png" alt="">
                      </div>
                    </div>
                    <div class="contact-fl-info">
                      <div>Butuh bantuan? Telepon kami!</div>
                      <div class="fl-usp-timing">
                        <?php
                        $week = date("w");
                        $from = "09.30";
                        $to = $week >=1 && $week <=3 ? '21.00' : '18.30';
                        $currentTime = (int) date('Gis');
                        if((int) str_replace('.', '', $from.'00') < $currentTime && (int)  str_replace('.', '', $to.'00') > $currentTime){
                          echo '<span class="fl-usp-timing-open">Hubungi sekarang</span>';
                        }else{
                          echo '<span class="fl-usp-timing-close">Tutup</span>';
                        }
                        ?>
                        &#8226; <?php echo $from; ?> - <?php echo $to; ?> WIB
                      </div>
                      <div class="fl-contact-no">
                        <a href="tel:02122775029">(021) 22775029</a>
                      </div>
                      <div>Whatsapp Fabelio ke: <a href="tel:081261144200">081261144200</a></div>
                    </div>
                  </div>
                  <?php if($_product->getData('manufacturer') == 167): ?>
                  <div class="fl-usps clearfix">
                    <div class="col-md-3 col-sm-6 col-xs-3">
                      <div class="icon">
                        <img src="/media/icons/pengiriman-gratis.png" alt="">
                      </div>
                      <p>Pengiriman Gratis</p>
                    </div>
                    <div class="col-md-3 col-sm-6 col-xs-3">
                      <div class="icon">
                        <img src="/media/icons/14-hari-pengembalian.png" alt="">
                      </div>
                      <p>14 Hari Pengembalian</p>
                    </div>
                    <div class="col-md-3 col-sm-6 col-xs-3">
                      <div class="icon">
                        <img src="/media/icons/garansi-365-hari.png" alt="">
                      </div>
                      <p>Garansi 365 Hari</p>
                    </div>
                    <div class="col-md-3 col-sm-6 col-xs-3">
                      <div class="icon">
                        <img src="/media/icons/cicilan-0.png" alt="">
                      </div>
                      <p>Cicilan 0%</p>
                    </div>
                  </div>
                  <?php endif; ?>
                </div>
                <div class="product-description_mobile_view">
                      <h3 class=" visible-xs visible-sm">Description</h3>
                      <h3 class=" hidden-xs"><?php echo $_product->getName(); ?></h3>
                      <?php echo $_product->getDescription(); ?>
                    </div>
              </form>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-8 border-right-desktop" >
              <div>
                <?php echo $this->getReviewsSummaryHtml($_product, false, true)?>
                <div class="product-collateral">
                    <?php echo $this->getChildHtml('product_additional_data'); ?>
                </div>
                <?php echo $this->getChildHtml('upsell_products'); ?>
              </div>
            </div>
            
            <div class="col-sm-4">
              <?php if($designer): ?>
              <div class="designer-block">
                <h3>Designer Information</h3>
                <h2><?php echo $manufacturerName; ?></h2>
                <div class="row">
                  <div class="col-md-6">
                  <img class="designer-img" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>wysiwyg/Designers/<?php echo $designer['img']; ?>">
                  </div>
                  <div class="col-md-6">
                  <p><?php echo $designer['about']; ?></p>
                  </div>
                </div>
              </div>
              <?php endif; ?>

              <?php if($manufacturer): ?>
              <div class="designer-block">
                <h3>Brand Information</h3>
                <h2><?php echo $manufacturerName; ?></h2>
                <div class="row">
                  <div class="col-md-6">
                    <a href="<?php echo $this->getUrl('brands' . '/' . $manufacturer['identifier']); ?>">
                      <img  class="designer-img"alt="<?php echo $manufacturer['manufacturer_logo'] ?>" title="<?php echo $manufacturerName ?>" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'manufacturer' . '/' . $manufacturer['manufacturer_logo'] ?>">
                    </a>
                  </div>
                  <div class="col-md-6">
                    <p>
                      <?php echo mb_strimwidth($manufacturer['description'], 0, 200, '&#8230;'); ?>
                      <br>
                      <a href="<?php echo $this->getUrl('brands' . '/' . $manufacturer['identifier']); ?>">Read More &gt;</a>
                    </p>
                  </div>
                </div>
              </div>
              <?php endif; ?>
            </div>

        </div>
<div id="TRUSTEDCOMPANY_widget_93284"><script async
src="https://d3643s33l1rfut.cloudfront.net/js/widget?w=BQYHDBEcXkxWQV5cRg"
></script></div>
<div id="TRUSTEDCOMPANY_widget_93286"><script async
src="https://d3643s33l1rfut.cloudfront.net/js/widget?w=BQYHDBEcXkxWQV5cRA"
></script></div>

<?php if(Mage::getStoreConfig('ajaxcart/addtocart/enableproduct') && (Mage::app()->getFrontController()->getRequest()->getModuleName() == "catalog") || (Mage::app()->getFrontController()->getRequest()->getModuleName() == "quickview")): ?>
    <script type="text/javascript">
    //<![CDATA[
        var productAddToCartForm = new VarienForm('product_addtocart_form');
        productAddToCartForm.submit = function(button, url) {
            if (this.validator.validate()) {
                var form = this.form;
                var oldUrl = form.action;

                if (url) {
                   form.action = url;
                }
                var e = null;
                if (!url) {
                    url = jQuery('#product_addtocart_form').attr('action');
                }
                if(url.indexOf("wishlist/index/cart") != -1){
                    url = url.replace("wishlist/index/cart","ajaxcart/index/add"); // New Code
                } else {
                    url = url.replace("checkout/cart","ajaxcart/index"); // New Code
                }
                url = url.replace("http://", "//");
                url = url.replace("https://", "//");
                var data = jQuery('#product_addtocart_form').serialize();
                data += '&isAjax=1';
                var is_quickview = false;
                if(jQuery("body").hasClass("quickview-index-view")){
                    is_quickview = true;
                }
                if(is_quickview)
                    window.parent.jQuery("#loading-mask").show();
                else
                    jQuery('#loading-mask').show();
                try {
                    jQuery.ajax({
                        url : url,
                        dataType : 'json',
                        type : 'post',
                        data : data,
                        success : function(data) {
                            if(is_quickview)
                                window.parent.jQuery('#loading-mask').hide();
                            else
                                jQuery('#loading-mask').hide();
                            if(data.status == 'ERROR'){
                                if(is_quickview)
                                    window.parent.alert(data.message.replace("<br/>",""));
                                else
                                    alert(data.message.replace("<br/>",""));
                            }else{
                                if(is_quickview){
                                    if(window.parent.jQuery('.header .mini-cart')){
                                        window.parent.jQuery('.header .mini-cart').replaceWith(data.toplink);
                                    }
                                    if(window.parent.jQuery('.fixed-header .mini-cart')){
                                        window.parent.jQuery('.fixed-header .mini-cart').replaceWith(data.toplink);
                                    }
									if(window.parent.jQuery('.sticky-header .mini-cart')){
										window.parent.jQuery('.sticky-header .mini-cart').replaceWith(data.toplink);
									}
                                    if(window.parent.jQuery('.col-right .block.block-cart')){
                                        window.parent.jQuery('.col-right .block.block-cart').replaceWith(data.cart_sidebar);
                                    }
                                    window.parent.jQuery('#after-loading-success-message #success-message-container .msg-box').html(data.message);
                                    <?php $autoclose = Mage::getStoreConfig('ajaxcart/addtocart/autoclose', $code);?>
                                    ajaxcart_sec = <?php echo ($autoclose && is_numeric($autoclose))?$autoclose:5; ?>;
                                    timer_sec = ajaxcart_sec;
                                    window.parent.jQuery('#after-loading-success-message').fadeIn(200);
                                    ajaxcart_timer = setInterval(function(){
                                        timer_sec --;
                                        window.parent.jQuery('#after-loading-success-message .timer').html(timer_sec);
                                    },1000)
                                    setTimeout(function(){
                                        window.parent.jQuery('#after-loading-success-message').fadeOut(200);
                                        clearTimeout(ajaxcart_timer);
                                        setTimeout(function(){
                                            window.parent.jQuery('#after-loading-success-message .timer').html(ajaxcart_sec);
                                        }, 1000);
                                    },ajaxcart_sec*1000);
                                }
                                else {
                                    if(jQuery('.header .mini-cart')){
                                        jQuery('.header .mini-cart').replaceWith(data.toplink);
                                    }
                                    if(jQuery('.fixed-header .mini-cart')){
                                        jQuery('.fixed-header .mini-cart').replaceWith(data.toplink);
                                    }
									if(jQuery('.sticky-header .mini-cart')){
										jQuery('.sticky-header .mini-cart').replaceWith(data.toplink);
									}
                                    if(jQuery('.col-right .block.block-cart')){
                                        jQuery('.col-right .block.block-cart').replaceWith(data.cart_sidebar);
                                    }
                                    jQuery('#after-loading-success-message #success-message-container .msg-box').html(data.message);
                                    <?php $autoclose = Mage::getStoreConfig('ajaxcart/addtocart/autoclose', $code);?>
                                    ajaxcart_sec = <?php echo ($autoclose && is_numeric($autoclose))?$autoclose:5; ?>;
                                    timer_sec = ajaxcart_sec;
                                    jQuery('#after-loading-success-message').fadeIn(200);
                                    ajaxcart_timer = setInterval(function(){
                                        timer_sec --;
                                        jQuery('#after-loading-success-message .timer').html(timer_sec);
                                    },1000)
                                    setTimeout(function(){
                                        jQuery('#after-loading-success-message').fadeOut(200);
                                        clearTimeout(ajaxcart_timer);
                                        setTimeout(function(){
                                            jQuery('#after-loading-success-message .timer').html(ajaxcart_sec);
                                        }, 1000);
                                    },ajaxcart_sec*1000);
                                }
                            }
                        }
                    });
                } catch (e) {
                }                
                this.form.action = oldUrl;
                if (e) {
                    throw e;
                }
            }
        }.bind(productAddToCartForm);
    //]]>
    </script>
<?php else : ?>
    <script type="text/javascript">
    //<![CDATA[
        var productAddToCartForm = new VarienForm('product_addtocart_form');
        productAddToCartForm.submit = function(button, url) {
            if (this.validator.validate()) {
                var form = this.form;
                var oldUrl = form.action;

                if (url) {
                   form.action = url;
                }
                var e = null;
                try {
                    this.form.submit();
                } catch (e) {
                }
                this.form.action = oldUrl;
                if (e) {
                    throw e;
                }

                if (button && button != 'undefined') {
                    button.disabled = true;
                }
            }
        }.bind(productAddToCartForm);
        //]]>
        </script>
        <?php endif; ?>
        <script type="text/javascript">
        productAddToCartForm.submitLight = function(button, url){
            if(this.validator) {
                var nv = Validation.methods;
                delete Validation.methods['required-entry'];
                delete Validation.methods['validate-one-required'];
                delete Validation.methods['validate-one-required-by-name'];
                // Remove custom datetime validators
                for (var methodName in Validation.methods) {
                    if (methodName.match(/^validate-datetime-.*/i)) {
                        delete Validation.methods[methodName];
                    }
                }

                if (this.validator.validate()) {
                    if (url) {
                        this.form.action = url;
                    }
                    this.form.submit();
                }
                Object.extend(Validation.methods, nv);
            }
        }.bind(productAddToCartForm);
    </script>
    </div>

</div>
<script type="text/javascript">
    jQuery(function($){
         
$(function() {
    function reposition() {
        var modal = $(this),
            dialog = modal.find('.modal-dialog');
        modal.css('display', 'block');
        
        // Dividing by two centers the modal exactly, but dividing by three 
        // or four works better for larger screens.
        dialog.css("margin-top", Math.max(0, ($(window).height() - dialog.height()) / 2));
    }
    // Reposition when a modal is shown
    $('.modal').on('show.bs.modal', reposition);
    // Reposition when the window is resized
    $(window).on('resize', function() {
        $('.modal:visible').each(reposition);
    });
});
        $("#main-slider-70").owlCarousel({

         autoPlay: false, //Set AutoPlay to 3 seconds

pagination:true,

navigation:true,

        items: 1,

        itemsDesktop: [1199, 1],

        itemsDesktopSmall: [979, 1],

       itemsMobile: [979, 1],
 navigationText: ["<img src='/skin/frontend/smartwave/porto/images/arrow-left.svg' />", "<img src='/skin/frontend/smartwave/porto/images/arrow-right.svg' />"]
       

  });  

        
        $("body.quickview-index-view .product-info a, body.quickview-index-view .no-rating a, body.quickview-index-view .ratings a").off('click').on("click",function(e){
            window.parent.location.href = $(this).attr("href");
            window.parent.jQuery.fancybox.close();
        });
    <?php
    if($enable_addtocart_sticky){
    ?>
        p_scrolled = false;
        $(window).scroll(function(){
            if(400<$(window).scrollTop() && !p_scrolled){
                $('.sticky-product').removeClass("hide");
                p_scrolled = true;
            }
            if(400>=$(window).scrollTop() && p_scrolled){
                $('.sticky-product').addClass("hide");
                p_scrolled = false;
            }
        });
    <?php
    }
    ?>
    <?php
    if($move_product_tab){
    ?>
        $(".product-info").before($(".product-tabs"));
    <?php
    }
    ?>
    });
    
    /** FAB-130 Start /**/
    jQuery(document).ready(function(){
        <?php
        $deliveryTime=Mage::app()->getRequest()->getParam('deliverytime');
        $deliveryTimes=explode('-',  $deliveryTime);
        $str='';
        foreach($deliveryTimes as $dt){
            $str.=$dt.',';
        }
        $str=  rtrim($str, ',');
        ?>
    var resultant=[<?php echo $str; ?>];
    
        
        var html='';
       
        <?php
    $attribute = Mage::getModel('eav/config')->getAttribute('catalog_product', 'deliverytime');
    $attributeArray=array();
    foreach ( $attribute->getSource()->getAllOptions(true, true) as $option){
        $attributeArray[]=$option;
    }
   
?>
         var atributes= <?php echo json_encode($attributeArray);?>;
         console.log(atributes);
        for(var i=0; i<resultant.length; i++){
            console.log(resultant[i]);
            for(var j=0; j<atributes.length; j++){
                if(parseInt(atributes[j].value)===parseInt(resultant[i])){
                    
                    html+='<li>'+atributes[j].label+' <span fid="'+atributes[j].value+'" class="removeFilter">x</span></li>';
                }
            }
            
        }
        console.log("kmal"+html);
        jQuery("#deliverytimefiltersselected").html(html);
        
        if(html===''){
            jQuery(".selected-attr").addClass("hide");
        }else{
            jQuery(".selected-attr").removeClass("hide");
        }
        jQuery(".removeFilter").click(function(){
            var fid= jQuery(this).attr("fid");
            var length=jQuery('#deliverytime-'+fid+'').length;
            
            jQuery('#deliverytime-'+fid+'').trigger("click");
        });
});
/** FAB-130 End /**/
</script>