<html>
    <head>    
        <link href="<?php echo $this->getJsUrl() ?>magestore/adminhtml/inventory/dashboard/lib/css.css" rel="stylesheet">
        <link href="<?php echo $this->getJsUrl() ?>magestore/adminhtml/inventory/dashboard/lib/dark.css" rel="stylesheet">
        <link href="<?php echo $this->getJsUrl() ?>magestore/adminhtml/inventory/dashboard/lib/blue.css" rel="stylesheet">    
        <script type="text/javascript" src="<?php echo $this->getJsUrl() ?>magestore/adminhtml/inventory/dashboard/lib/js"></script>
        <script type="text/javascript" src="<?php echo $this->getJsUrl() ?>magestore/adminhtml/inventory/dashboard/lib/js_003"></script>        
        
        <!-- charts -->
        <!--<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"></script>-->
        <script type="text/javascript" src="<?php echo $this->getJsUrl() ?>magestore/adminhtml/inventory/dashboard/lib/charts/highcharts.js"></script>
<script type="text/javascript" src="<?php echo $this->getJsUrl() ?>magestore/adminhtml/inventory/dashboard/lib/charts/modules/exporting.js"></script>
    </head>
</html>