<?php
$helper = Mage::helper("fabmod_criteo");
if (!$helper->isTagsEnabled()) {
  return;
}
$hashedEmail="";
if (Mage::getSingleton('customer/session')->isLoggedIn()){
	$customerEmail = Mage::getSingleton('customer/session')->getCustomer()->getEmail();
	$hashedEmail = md5($customerEmail);
}
$products = Mage::getBlockSingleton('catalog/product_list')->getLoadedProductCollection();
$ids = '';
$i=0;
foreach ($products as $item) {
	if($i<3){
			$i++;
			if ($ids !== '') {
			 $ids .= ', ';
			}
			$ids .= "'" . $item->getId() . "'";
		}
	}
?>
<script type="text/javascript">
var dataLayer = dataLayer || [];
dataLayer.push({
	'PageType': 'Listingpage',
	'HashedEmail': '<?php echo $hashedEmail; ?>', 
	'ProductIDList': [<?php echo $ids; ?>]
});
</script>