<?php
$helper = Mage::helper("fabmod_criteo");
if (!$helper->isTagsEnabled()) {
  return;
}
$hashedEmail="";
if (Mage::getSingleton('customer/session')->isLoggedIn()){
	$customerEmail = Mage::getSingleton('customer/session')->getCustomer()->getEmail();
	$hashedEmail = md5($customerEmail);
}
?>
<script type="text/javascript">
var dataLayer = dataLayer || [];
dataLayer.push({
	'PageType': 'Homepage', 
	'HashedEmail': '<?php echo $hashedEmail; ?>', 
});
</script>
