<?php
$helper = Mage::helper("fabmod_criteo");
if (!$helper->isTagsEnabled()) {
  return;
}
$hashedEmail="";
if (Mage::getSingleton('customer/session')->isLoggedIn()){
	$customerEmail = Mage::getSingleton('customer/session')->getCustomer()->getEmail();
	$hashedEmail = md5($customerEmail);
}
$_product = Mage::registry('current_product');
?>
<script type="text/javascript">
var dataLayer = dataLayer || [];
dataLayer.push({
	'PageType': 'Productpage',
	'HashedEmail': '<?php echo $hashedEmail; ?>', 
	'ProductID': '<?php echo $_product->getId(); ?>'
});
</script>