<?php
$helper = Mage::helper("fabmod_criteo");
if (!$helper->isTagsEnabled()) {
  return;
}
$hashedEmail="";
if (Mage::getSingleton('customer/session')->isLoggedIn()){
  $customerEmail = Mage::getSingleton('customer/session')->getCustomer()->getEmail();
  $hashedEmail = md5($customerEmail);
}
$orderId = Mage::getSingleton('checkout/session')->getLastRealOrderId();
if ($orderId) {
    $order = Mage::getModel('sales/order')->loadByAttribute('increment_id', $orderId);
    $items = $order->getAllItems();
    $ids = array();
    foreach ($items as $item) {
       $ids[] = '{id:"' . $item->getProduct()->getId() . '",price:'.$item->getProduct()->getFinalPrice().',quantity:'.$item->getQtyOrdered().'}';
    }
}

?>


<script type="text/javascript">
var dataLayer = dataLayer || [];
var products_list = [];
products_list.push(
  <?php echo join(',', $ids); ?>
);

dataLayer.push({
  'PageType': 'Transactionpage',
  'HashedEmail': '<?php echo $hashedEmail; ?>', 
  'ProductTransactionProducts': products_list,
  'TransactionID': '<?php echo $orderId; ?>'
});
</script>
