<?php
/**
 * Magento
 *
 * @author    WakaMage http://www.wakamage.com <cs@wakamage.com>
 * @copyright Copyright (C) 2013 WakaMage. (http://www.wakamage.com)
 *
 */
?>
<!--<ul class="form-list" id="payment_form_<?php //echo $this->getMethodCode() ?>" style="display:none;">
    <li class="form-alt"><?php //echo $this->getRedirectMessage() ?></li>
</ul>-->
<?php $_coreHelper = Mage::helper('core'); ?>
<?php $_code=$this->getMethodCode() ?>
 <?php $total = $this->helper('checkout/cart')->getQuote()->getGrandTotal();
$threeMonths = sprintf('%0.2f', $total/3);
 $sixMonths = sprintf('%0.2f', $total/6);
 $twelveMonths = sprintf('%0.2f', $total/12);?>
<div class="bank-cicilan-inner" id="payment_form_<?php echo $_code ?>" >
<label style="width:35%;">Tenor</label>
 <select id="bca_credit_installment" name="payment[bca_credit_installment]" class="installment_select">
     <option value="bca3">no installment</option>
<option value="bca3">3 months x <?php echo $_coreHelper->formatPrice($threeMonths, false); ?></option>
<option value="bca6">6 months x <?php echo $_coreHelper->formatPrice($sixMonths, false); ?></option>
 <option value="bca12">12 months x <?php echo $_coreHelper->formatPrice($twelveMonths, false); ?></option>
</select>
<!--<div>
<?php //echo $this->getMethod()->getConfigData('message');?>
</div>-->
</div>
