<?php
    $helper = Mage::helper("porto");
    //$_product = Mage::registry("current_product");
    $_product = $this->getProduct();
    if($_product == NULL){
      $_product = Mage::registry("current_product");
    }
    $product_id = $_product->getId();
?>

<?php
  $tabs = $this->getTabs();
  if(!$tabs){
    $tabs = array();
  }
  $description = null;
  foreach ($tabs as $_index => $_tab){
    if($_tab['alias'] == 'description_tabbed') {
      $description = $_tab;
      unset($tabs[$_index]);
    }
  }
?>

<?php if($this->getChildHtml($description['alias'])): ?>
<div class="product-description product-des-desktop">
  <h3 class="hidden-xs hidden-sm"><?php echo $description['title']?></h3>
  <h3 class="visible-xs visible-sm"><?php echo $_product->getName(); ?></h3>
  <?php echo $this->getChildHtml($description['alias']); ?>
</div>
<script type="text/javascript">
  (function($){
    $('.product-img-box').after($('.product-description'));
  }(jQuery));
</script>
<?php endif; ?>

<div class="product-tabs">
    <ul class="clearfix product-tabs-nav">
        <?php foreach ($tabs as $_index => $_tab): ?>
            <?php if($this->getChildHtml($_tab['alias'])): ?>
                <li id="tab_<?php echo $_tab['alias'] ?>"><a><?php echo $_tab['title']?></a></li>
            <?php endif; ?>
        <?php endforeach; ?>

        <?php
        for($j=1;$j<=4;$j++){
            $custom_tab = "attribute_tab_".$j;
            $custom_tab_title = $helper->getTabTitle("attribute", $custom_tab, $product_id);
            //if($helper->isEnabledTab("attribute", $custom_tab, $product_id)){
            if($custom_tab_title){
        ?>
                <li id="tab_<?php echo $custom_tab ?>"><a><?php echo $custom_tab_title ?></a></li>
        <?php
            }
        }
        ?>

        <?php
        for($k=1;$k<=5;$k++){
            $custom_tab = "static_block_tab_".$k;
            if($helper->isEnabledTab("static_block", $custom_tab, $product_id)){
        ?>
                <li id="tab_<?php echo $custom_tab ?>"><a><?php echo $helper->getTabTitle("static_block", $custom_tab, $product_id)?></a></li>
        <?php
            }
        }
        ?>
    </ul>

    <?php foreach ($tabs as $_index => $_tab): ?>
        <?php if($this->getChildHtml($_tab['alias'])): ?>
            <div class="tab-content" id="tab_<?php echo $_tab['alias'] ?>_contents">
              <?php echo $this->getChildHtml($_tab['alias']) ?>
            </div>
        <?php endif; ?>
    <?php endforeach; ?>

    <?php
    for($i=1;$i<=4;$i++){
        $custom_tab = "attribute_tab_".$i;
        $custom_tab_title = $helper->getTabTitle("attribute", $custom_tab, $product_id);
        //if($helper->isEnabledTab("attribute", $custom_tab, $product_id)){
        if($custom_tab_title){
    ?>
            <div class="tab-content" id="tab_<?php echo $custom_tab ?>_contents">
              <?php echo $helper->getTabContents("attribute", $custom_tab, $product_id); ?>
            </div>
    <?php
        }
    }
    ?>

    <?php
    for($i=1;$i<=5;$i++){
        $custom_tab = "static_block_tab_".$i;
        if($helper->isEnabledTab("static_block", $custom_tab, $product_id)){
    ?>
            <div class="tab-content" id="tab_<?php echo $custom_tab ?>_contents">
              <?php echo $helper->getTabContents("static_block", $custom_tab, $product_id)?>
            </div>
    <?php
        }
    }
    ?>
    <script type="text/javascript">
    new Varien.Tabs('.product-tabs ul');
    </script>
</div>
