<?php
if (Mage::getSingleton('customer/session')->isLoggedIn()) { $customer = Mage::getSingleton('customer/session')->getCustomer(); $email_id = $customer->getEmail();}
?>
<!-- FAB-62 Ematic JS---- code start -->
<script>

    (function(i,s,o,g,r,a,m){i['EmaticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//api.ematicsolutions.com/v1/ematic.min.js','ematics');
 
    var ematicApikey = "6d91c1bbf1ad11e5a40a0242ac110015-sg1";
    var opt = {
        email: "<?php echo $email_id ?>",
        country_iso: "ID",
        currency_iso: "IDR",
        language_iso: "IN"
    };
    
    //initialize
    ematics("create", ematicApikey, opt);
</script>
<!-- FAB-62 Ematic JS---- code end -->
