<?php
$showTrustedWidget = 0;
$mediaUrl = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA);
$store = Mage::app()->getStore();
$code  = $store->getCode();
$footer = Mage::getStoreConfig('porto_settings/footer',$code);
$footer_class = ($footer['fixed_position_footer_enabled'])?" fixed-position":"";
?>

<?php
if($this->getUrl('') == $this->getUrl('*/*/*', array('_current'=>true, '_use_rewrite'=>true)))
{
  $showTrustedWidget = 1;
}
elseif(Mage::registry('current_product'))
{
  $showTrustedWidget = 1;
}
else
{
  $request = $this->getRequest();
  $module = $request->getModuleName();
  $controller = $request->getControllerName();
  $action = $request->getActionName();
  if($module == 'checkout' && $controller == 'cart' && $action == 'index')
  {
    $showTrustedWidget = 1;
  }   
}
if($showTrustedWidget == 1)
{
?>
<!--<div id="TRUSTEDCOMPANY_widget_93284"><script async
src="https://d3643s33l1rfut.cloudfront.net/js/widget?w=BQYHDBEcXkxWQV5cRg"
></script></div>
<div id="TRUSTEDCOMPANY_widget_93286"><script async
src="https://d3643s33l1rfut.cloudfront.net/js/widget?w=BQYHDBEcXkxWQV5cRA"
></script></div>-->
<?php }
?>



   <div class="seo-text-container visible-lg-block visible-md-block hidden-xs hidden-sm container">
<?php
$curr_category = Mage::registry('current_category');
if(Mage::registry('current_product')){
  //  echo "u r in product page";
}elseif(Mage::registry('current_category')){
  //  echo "you are in category page";
  $_seo_category_name = $curr_category->getName().' di Fabelio';
  $catname_block      = 'category_'.$curr_category->getId(); ?>
                      <p> <?php  echo $_seo_category_name ; ?></p>
                      <div class="seo-text">
                        <p><?php echo $this->getLayout()->createBlock('cms/block')->setBlockId($catname_block)->toHtml(); ?></p>
                      </div> 
<?php
}else{
  //  echo  "you are in other page";
}    
?>
    </div>       


<div class="footer-container <?php echo $footer_class; ?>">
    <div class="footer">
      <div class="footer-subscribe clearfix">
        <div class="container">
          <div class="col-sm-9">
            <?php echo $this->getChildHtml('footer.newsletter_form'); ?>
          </div>
          <div class="col-sm-3">
<?php
if($footer['footer_bottom_socialicons']){
  echo $this->getChildHtml('socialicons');
}
?>
          </div>
        </div>
      </div>
<!--footer image code-->
 <div class="footer-subscribe clearfix">
        <div class="container">
          <div class="col-sm-6" style="border-right: 1px solid #ccc;">
<p class="footer-incentive">Partner Pembayaran Kami</p>
 <img src="<?php echo $mediaUrl.'images/footer_images/footer-bank/veritrans-footer.png';?>"/>
 <img src="<?php echo $mediaUrl.'images/footer_images/footer-bank/sprint-footer.png';?>"/>
          </div>
           <div class="col-sm-6">
<p class="footer-incentive">Partner Logistik</p>
 <img src="<?php echo $mediaUrl.'images/footer_images/logistic_logos/pandu-logistic.png';?>" style="width:88px;"/>
 <img src="<?php echo $mediaUrl.'images/footer_images/logistic_logos/platinium-logistics.png';?>" style="width:88px;"/>
 <img src="<?php echo $mediaUrl.'images/footer_images/logistic_logos/dakota-cargo.png';?>" style="width:88px;"/>
 <img src="<?php echo $mediaUrl.'images/footer_images/logistic_logos/21-express.png';?>" style="width:88px;"/>
          </div>

        </div>
      </div>

<!---footer image code ends-->

<?php
if( $footer['footer_top_enabled'] ){
?>
        <div class="footer-top">
            <div class="container">
                <div class="row">
                    <div class="col-sm-12">
<?php
  $area = 'footer_top_block';
  $type = $footer[$area];
  if( $type== 'twitter' ){
    echo $this->getChildHtml('tweets');
  }
  if( $type == 'custom' ){
    echo $this->getLayout()->createBlock('cms/block')->setBlockId($footer['footer_top_custom'])->toHtml();
  }
?>
                    </div>
                </div>
            </div>
        </div>
<?php
}
if( $footer['footer_middle_enabled'] ){
?>
        <div class="footer-middle hidden-sm hidden-xs">
            <div class="container">
<?php
  if( $footer['footer_ribbon_enabled'] ){
?>
                <div class="footer-ribbon">
                    <span><?php echo $footer['footer_ribbon_text'] ?></span>
                </div>
<?php
  }
?>
                <div class="row">
<?php
  for( $i = 1; $i <= 4; $i++ ){
    $area = 'footer_middle_column_'.$i;
    $type = $footer[$area];
    if( $type ){
      echo '<div class="col-sm-3">';
    }
    if( $type == 'custom' ){
      echo $this->getLayout()->createBlock('cms/block')->setBlockId($footer[$area.'_custom'])->toHtml();
    }
    if( $type == 'newsletter' ){
      echo $this->getChildHtml('footer.newsletter');
    }
    if( $type== 'facebook' ){
      echo $this->getChildHtml('facebook_fans');
    }
    if( $type== 'flickr' ){
      echo $this->getChildHtml('flickr');
    }
    if( $type== 'twitter' ){
      echo Mage::getSingleton("core/layout")->getBlock("tweets")->setTemplate("socialfeeds/footer_middle_twitterfeed.phtml")->toHtml();
    }
    if( $type ){
      echo '</div>';
    }
?>
<?php
  }
?>
                </div>
                <?php echo $this->getChildHtml("demo_footer_tooltip"); ?>
            </div>
        </div>
<?php
}
if( $footer['footer_middle_2_enabled'] ){
?>
        <div class="footer-middle footer-middle-2 hidden-sm hidden-xs">
            <div class="container">
                <div class="row">
<?php
  for( $i = 1; $i <= 4; $i++ ){
    $area = 'footer_middle_2_column_'.$i;
    $type = $footer[$area];
    if( $type ){
      echo '<div class="col-sm-3">';
    }
    if( $type == 'custom' ){
      echo $this->getLayout()->createBlock('cms/block')->setBlockId($footer[$area.'_custom'])->toHtml();
    }
    if( $type == 'newsletter' ){
      echo $this->getChildHtml('footer.newsletter');
    }
    if( $type== 'facebook' ){
      echo $this->getChildHtml('facebook_fans');
    }
    if( $type== 'flickr' ){
      echo $this->getChildHtml('flickr');
    }
    if( $type ){
      echo '</div>';
    }
?>
<?php
  }
?>
                </div>
            </div>
        </div>
<?php
}
if( $footer['footer_bottom_enabled'] ){
?>
        <div class="footer-bottom hidden-sm hidden-xs">
            <div class="container">
<?php
  if($footer['footer_logo']){
?>
                    <a href="<?php echo $this->getUrl('') ?>" class="logo"><img src="<?php echo $this->getSkinUrl($footer['footer_logo']); ?>" alt=""/></a>
<?php
  }
?>
<?php
  if($footer['footer_bottom_custom_block'] && $footer['footer_bottom_custom_block_id']){
    echo '<div class="custom-block">'.$this->getLayout()->createBlock('cms/block')->setBlockId($footer['footer_bottom_custom_block_id'])->toHtml().'</div>';
  }
?>
<?php
  if($footer['footer_bottom_custom_block_2'] && $footer['footer_bottom_custom_block_id_2']){
    echo '<div class="custom-block f-right">'.$this->getLayout()->createBlock('cms/block')->setBlockId($footer['footer_bottom_custom_block_id_2'])->toHtml().'</div>';
  }
?>
                <address><?php echo $footer['copyrights'] ?></address>


            </div>
        </div>
        <div class="footer-bottom visible-sm visible-xs">
            <div class="container">
                <div class="footer-bottom-links">
                  <a href="/kebijakan-privasi">Kebijakan Privasi</a> |
                  <a href="/syarat-dan-ketentuan">Syarat dan Ketentuan</a> |
                  <a href="/faq">FAQ</a>
                </div>
                <address><?php echo $footer['copyrights'] ?></address>
            </div>
        </div>
<?php
}
?>
    </div>
</div>
<!-- <a href="#" id="totop"><i class="icon-up-open"></i></a>-->
<script type="text/javascript">
    /*var windowScroll_t;
  jQuery(window).scroll(function(){
        clearTimeout(windowScroll_t);
        windowScroll_t = setTimeout(function(){
            if(jQuery(this).scrollTop() > 100){
                jQuery('#totop').fadeIn();
            }else{
                jQuery('#totop').fadeOut();
            }
        }, 500);
    });
    jQuery('#totop').click(function(){
        jQuery('html, body').animate({scrollTop: 0}, 600);
        return false;
    });*/
jQuery(function($){
  $(".cms-index-index .footer-container.fixed-position .footer-top,.cms-index-index .footer-container.fixed-position .footer-middle").remove();
});
</script>
