<meta http-equiv="Content-Type" content="<?php echo $this->getContentType() ?>" />
<?php if($meta_title=$this->getMetaTitle()): ?>
<title><?php echo htmlspecialchars($meta_title) ?></title>
<?php else: ?>
<title><?php echo $this->getTitle() ?></title>
<?php endif; ?>
<meta name="description" content="<?php echo htmlspecialchars($this->getDescription()) ?>" />
<meta name="keywords" content="<?php echo htmlspecialchars($this->getKeywords()) ?>" />
<meta name="robots" content="<?php echo htmlspecialchars($this->getRobots()) ?>" />
<meta name="viewport" content="width=device-width, initial-scale=1.0"/>
<link rel="icon" href="<?php echo $this->getFaviconFile(); ?>" type="image/x-icon" />
<link rel="shortcut icon" href="<?php echo $this->getFaviconFile(); ?>" type="image/x-icon" />

<?php //Include Google fonts character subsets (such as extended latin, cyrillic)
    $theme = Mage::helper('porto');
    $charSubset = '&subset=latin';
    $d = $theme->getCfgSectionDesign();
    if (isset($d['font']['primary_char_latin_ext']) && $d['font']['primary_char_latin_ext']==1 )
        $charSubset .= ',latin-ext';
    if (isset($d['font']['custom_char_subset']) && $d['font']['custom_char_subset'])
        $charSubset .= ','.$d['font']['custom_char_subset'];
    $font_sizes = "%3A300%2C300italic%2C400%2C400italic%2C600%2C600italic%2C700%2C700italic%2C800%2C800italic";
?>
<?php if ($d['font']['custom'] && $d['font']['primary_font_family_group'] == 'google'): ?>
<link rel="stylesheet" href='//fonts.googleapis.com/css?family=<?php echo str_replace(' ', '+', $d['font']['primary_font_family']).$font_sizes; echo $charSubset; ?>' type='text/css' />
<?php else: ?>
<link rel="stylesheet" href="//fonts.googleapis.com/css?family=Roboto:400,300italic,300,100italic,100,400italic,500,500italic,700,700italic,900,900italic" type="text/css" media="screen"/>
<?php endif;?>
<link href='//fonts.googleapis.com/css?family=Shadows+Into+Light' rel='stylesheet' type='text/css'/>
<?php echo $this->getCssJsHtml() ?>
<?php echo $this->getChildHtml() ?>
<?php echo $this->helper('core/js')->getTranslatorScript() ?>
<?php echo $this->getIncludes() ?>
<script type="text/javascript">
    wow = new WOW(
      {
        animateClass: 'animated',
        offset:       100
      }
    );
    wow.init();
</script>

<!--<?php echo "Porto Magento Theme: v".Mage::getConfig()->getModuleConfig("Smartwave_Porto")->version; ?>-->
<?php  
if (Mage::getSingleton('customer/session')->isLoggedIn()) {
    $customer = Mage::getSingleton('customer/session')->getCustomer();
    $customer_email = $customer->getEmail();
}
$cartProductArray = array();
$cart = Mage::getModel('checkout/cart')->getQuote();
foreach ($cart->getAllItems() as $item)
{
$productName = $item->getProduct()->getName();
$productPrice = $item->getProduct()->getPrice();
$formattedPrice = Mage::helper('core')->currency($productPrice, true, false);
$productQty = $item->getQty();
$productId = $item->getId();
$productSku = $item->getSku();
$product = Mage::getModel('catalog/product')->loadByAttribute('sku', $productSku);
$categoryIds = $product->getCategoryIds();
$productBrandName = $item->getProduct()->getAttributeText('manufacturer');
$productDescription = $product->getDescription();
$productImageUrl = Mage::helper('catalog/image')->init($product, 'thumbnail');
$productUrl = $product->getProductUrl();
//echo "CategoryId".$categoryIds[0]."Price:".$formattedPrice."Quantity:".$productQty."Name:".$productName."desc:".$productDescription."brandNa$
$cartProductArray[] = array("id" => $productId,
                                        "categoryId" => trim($categoryIds[0]),
                                        "transactionId" => "",
                                        "price" => trim($formattedPrice),
                                        "quantity" => trim($productQty),
                                        "name" => trim($productName),
                                        "brandName" => trim($productBrandName),
                                        "desc" => trim($productDescription),
                                        "imageUrl" => trim($productImageUrl),
                                        "link" => trim($productUrl));
}
global $jsonEncodedCartData;
$jsonEncodedCartData = json_encode($cartProductArray);
$session = Mage::getSingleton("core/session");
$session->setData("sessionJsonEncodedCartData", $jsonEncodedCartData);
?>
<!-- FAB-62 Ematic JS---- code start -->
<script>
    (function(i,s,o,g,r,a,m){i['EmaticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//api.ematicsolutions.com/v1/ematic.min.js','ematics');
 
    var ematicApikey = "c31fa675f1ad11e5a40a0242ac110015-sg1";
    var opt = {
        email: "<?php echo $customer_email ?>",
        country_iso: "ID",
        currency_iso: "IDR",
        language_iso: "IN"
    };
    
    //initialize
    ematics("create", ematicApikey, opt);
</script>
<!-- FAB-62 Ematic JS---- code end -->
