<?php

/**

 * Veritrans VT Web Model Standard

 *

 * @category   Mage

 * @package    vtweb/form.phtml

 * @author     Kisman Hong, plihplih.com

 * this template is rendered when Veritrans payment method is chosen. This is description about Veritrans Payment Method

 */

?>

<?php

$enable_payment = $this->getEnablePayment();

$direct_debit = $this->getDirectDebit();

$emoney = $this->getEmoney();

$cc =  $this->getCreditCard();

$bank_trans = $this->getBankTransfer();

$cstore = $this->getCstore();

?>



<style>

.border

{

    border-style:solid; 

    border-width:1px; 

    border-color:#cccccc; 

    height: 38px;

}

.image

{

    height:30px;

    width:50px;

    margin:10px 3px;

    padding:0 0 0 4;

}

.float

{

    float:left;

}

.float-group

{

    float:left;

    margin:10px 8px 0 0;



}

.displayed

{

    display: block;

    margin: auto;

}

</style>



<div role="tabpanel" class="tab-pane active" id="home">
                          <div class="bank-logo-inner">
                            <img src="<?php echo $this->getSkinUrl('images/veritrans.png'); ?>" width="120" style="margin-bottom:20px;" />
                              <p>
                                Veritrans adalah partner pembayaran online kami. Kami akan membawa Anda ke
                                halaman website Veritrans (www.veritrans.co.id) setelah mengklik tombol dibawah ini.
                                Kami akan mengirim email kepada Anda apabila transaksi telah berhasil.
                              </p>
                            <p>

                                Veritans menerima metode pembayaran sebagai berikut:
                            </p>

                            <ul class="bank-logo-main">
                              <li><img src="<?php echo $this->getSkinUrl('images/vt-visa.png'); ?>" alt="visa" /></li>
                              <li><img src="<?php echo $this->getSkinUrl('images/vt-mastercard.png'); ?>" alt="mastercard" /></li>
                              <li><img src="<?php echo $this->getSkinUrl('images/vt-jcb.png'); ?>" alt="jcb" /></li>
                              <li><img src="<?php echo $this->getSkinUrl('images/vt-atmbersama.png'); ?>" alt="atmbersama" /></li>
                              <li><img src="<?php echo $this->getSkinUrl('images/vt-prima.png'); ?>" alt="prima" /></li>
                              <li><img src="<?php echo $this->getSkinUrl('images/vt-alto.png'); ?>" alt="alto" /></li>
                            </ul>

                            <div class="bank-page-total">
                              <div class="bank-page-inner">
                                <label>Grand Total</label>
                                <span>
                                    <?php
                                        $_coreHelper = Mage::helper('core');
                                        $totals = Mage::getSingleton('checkout/session')->getQuote()->getTotals(); //Total object
                                        $grandtotal = $totals["grand_total"]->getValue(); //Grandtotal value 
                                        echo $formattedPrice = $_coreHelper->formatPrice($grandtotal , false);
                                    ?>   
                                </span>
                              </div>

                              <div class="bank-page-inner bank-lower-total">
                                <label>Total Dibayarkan</label>
                                <span>
                                    <?php
                                        $_coreHelper = Mage::helper('core');
                                        $totals = Mage::getSingleton('checkout/session')->getQuote()->getTotals(); //Total object
                                        $grandtotal = $totals["grand_total"]->getValue(); //Grandtotal value 
                                        echo $formattedPrice = $_coreHelper->formatPrice($grandtotal , false);
                                    ?>   
                                </span>
                              </div>
                            </div>

<!--                            <div class="checkout-item-button">
                              <a href="" class="chkbtn btn-checkout">Konfirmasi Pesanan</a>
                            </div>-->
                          </div>

                      </div>


<!--FAB-85 code start -->

