<?php $_items = $this->getOrder()->getShipmentsCollection(); ?>
<h2 class="sub-header"><?php echo $this->__("Shipments"); ?></h2>
<div class="table-responsive">
    <table class="table table-striped">
        <thead>
        <tr>
            <th><?php echo $this->__('Shipping Number'); ?></th>
            <th><?php echo $this->__('Date'); ?></th>
            <th><?php echo $this->__('Tracking Number'); ?></th>
            <th><?php echo $this->__('Action'); ?></th>
        </tr>
        </thead>
        <tbody>
        <?php if($_items->getSize() && count($_items->getData()) > 0): ?>
            <?php foreach($_items AS $_item) : ?>
                <?php $tracks = $_item->getAllTracks(); ?>
                <tr>
                    <td><?php echo $_item->getIncrementId(); ?></td>
                    <td><?php echo $_item->getCreatedAt(); ?></td>
                    <td><?php echo (count($tracks) > 0 ?  '#'.$tracks[0]->getData('track_number') : ''); ?></td>
                    <td> <a href="<?php echo Mage::getUrl('*/shipment/view/', array('id' => $_item->getId())) ?>" class="btn btn-primary"><?php echo $this->__('View'); ?></a></td>
                </tr>
            <?php endforeach; ?>
        <?php else: ?>
            <td colspan="3"><?php echo $this->__("No Shipments"); ?></td>
            <td><a href="<?php echo Mage::getUrl('marketplace/shipment/create/', array('id' => $this->getOrder()->getId())) ?>" class="btn btn-primary"><?php echo $this->__('Create'); ?></a></td>
        <?php endif; ?>
        </tbody>
    </table>
</div>
