<?php $_items = $this->getCollection(); ?>
<div class="container-fluid main-container vendor-container">
        <h1><?php echo $this->__($this->getTitle()) ?></h1>
        <div class="jumbotron">
            <form name="report_filter" id="report_filter" action="<?php echo Mage::getUrl('*/*/*') ?>" method="post" enctype="multipart/form-data">
                <div class="row">
                    <div class="col-md-2">
                        <select id="sales_report_period_type" name="period_type" title="Period" class="form-control select">
                            <option value="day">Day</option>
                            <option value="month">Month</option>
                            <option value="year">Year</option>
                        </select>
                    </div>
                    <div class="col-md-3">
                        <input type="text" class="form-control datepicker input-text required-entry" name="from" value="<?php echo $this->getRequest()->getPost('from', ''); ?>" placeholder="From *"/>
                    </div>
                    <div class="col-md-3">
                        <input type="text" class="form-control datepicker input-text required-entry" name="to" value="<?php echo $this->getRequest()->getPost('to', ''); ?>" placeholder="To *"/>
                    </div>
                    <div class="col-md-2">
                        <input type="submit" name="submit" class="btn btn-primary btn-sm" value="<?php echo $this->__('Show Report') ?>" />
                    </div>
                    <div class="col-md-2">
                        <input type="submit" name="submit" class="btn btn-sm" value="<?php echo $this->__('Export to CSV') ?>" />
                    </div>
                </div>
            </form>
        </div>
    <script type="text/javascript">
        //< ![CDATA[
        var customForm = new VarienForm('report_filter');
        //]]>
        jQuery(document).ready(function($){
            $('.datepicker').datepicker();
        });
    </script>
    <div class="table-responsive">
        <table class="table table-striped">
            <thead>
            <tr>
                <th><?php echo $this->__('Product Name'); ?></th>
                <th><?php echo $this->__('Product SKU'); ?></th>
                <th><?php echo $this->__('Stock Qty'); ?></th>
            </tr>
            </thead>
            <tbody>
                <?php $sumItemCount = 0; ?>
                <?php $sumQtySold = 0; ?>
                <?php $sumSubtotal = 0; ?>
                <?php $sumIncome = 0; ?>
                <?php if($_items->count() > 0): ?>
                    <?php foreach($_items AS $_item) : ?>
                        <tr>
                            <td><?php echo $_item->getName(); ?></td>
                            <td><?php echo $_item->getSku(); ?></td>
                            <td><?php echo number_format($_item->getQty()); ?></td>
                        </tr>
                    <?php endforeach; ?>
            <?php else : ?>
                    <tr>
                        <td colspan="4" class="text-center"><?php echo $this->__('No records found.'); ?></td>
                    </tr>
            <?php endif; ?>
            </tbody>
            <tfoot>
            <tr>
                <td class="info" colspan="1"><?php echo $this->__('Total'); ?></td>
                <td class="info"></td>
                <td class="info"><?php echo $sumQtySold; ?></td>
            </tr>
            </tfoot>
        </table>
    </div>
</div>